### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DerNorbert**
added Slackware

### CODE REVIEW

**Comment by jwilm** [comment]
Was this tested with a fresh install? I'm just concerned that your system may have already had required dependencies from some action you took versus the OS providing them as part of stock distribution.

**Comment by DerNorbert** [comment]
Well, not a fresh install, but I just have few packages on top, none of which is a dependency for the other distros. As Slackwares .tgz package management compiles everything you want to add from 3rd party repos "normal" stuff needed to compile is already included. At least in the default (full) install.

**Comment by DerNorbert** [comment]
Hmm, no copy & paste here. Installed xclip, which wasn't on my machine, but still no copy & paste...

**Comment by jwilm** [comment]
@DerNorbert do you get an error message in Alacritty's controlling terminal when trying to copy or paste?

**Comment by DerNorbert** [comment]
@jwilm no, I just have no possibility to paste. Neither [ctrl][v], nor right-click triggers any action. The only message is during startup:
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)

**Comment by jwilm** [comment]
Middle mouse should be paste by default. Pasting should either work or print some sort of error message.

**Comment by DerNorbert** [comment]
Ok, that's the only way I can't paste due to 2 button trackball. Will try middle button emulation and report :-)

**Comment by DerNorbert** [comment]
@jwilm thanks for the hint, i activated middle mouse emulation and it worked :+1: 
I updated the readme.

Many thanks for your work, now my terminator can retire :-)

**Comment by jwilm** [comment]
Would you mind squashing these commits?

**Comment by DerNorbert** [comment]
No, certainly not. 
Ah - one more question: Now I can paste to alacritty, but how can I copy from it? :-)

**Comment by jwilm** [comment]
On Linux, selecting text should automatically load it into the selection buffer. You can also change the keybindings to trigger a copy.

**Comment by DerNorbert** [comment]
Gnah, should have been taken a look at the config by myself, thanks, works like a charm :-)

**Comment by jwilm** [comment]
Were you going to rebase and squash this?

**Comment by DerNorbert** [comment]
Ahm, no, Github won't let me push sth, so I just changed it in the webeditor. Also I have no option to squash or merge, please can you do it.

**Comment by jwilm** [comment]
Landed in 4ebcbf1c4d02d83b023cdb93a521b55a150418ee

**Pull request closed without merging**
