### PR TITLE
Fix macOS OpenGL context resize ordering

### LINKED ISSUE #2226: Padding does not take effect until I start typing
Which operating system does the issue occur on?

macOS 10.14.4

I have Alacritty's window padding settings set to the default of:

```
  padding:
    x: 10
    y: 10
```

When I open a new Alacritty window, there is 0 padding, but when I begin to type the padding setting goes into effect and is set to `10px`.

I've tried removing my config file and uninstalling and reinstalling Alacritty, but it still does this even with a fresh install.

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #2226.

### CODE REVIEW

**Comment by kchibisov** [comment]
Could you also test #889 . IIRC it was also related to resize, maybe it do something about it.

**Comment by kchibisov** [comment]
Seems like it's working fine on X11/Wayland on my system.

**Comment by chrisduerr** [comment]
> Could you also test #889 . IIRC it was also related to resize, maybe it'll do something about it.

That's a great idea, I'll get on that later.

**Comment by chrisduerr** [comment]
There's no change to #889 as far as I can tell.

**Pull request merged**
