### PR TITLE
Adding snapcraft.yaml

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
[Snapcraft](https://snapcraft.io/) makes Linux packaging very simple in a cross-distro
way. This adds the snapcraft.yaml file to setup a snap of
alacritty.

### CODE REVIEW

**Comment by ChrisMacNaughton** [comment]
I have already registered the snap package name alacritty, will pass ownership of that over and am happy to help with setting up automated builds!

**Comment by ChrisMacNaughton** [comment]
The builders at https://build.snapcraft.io/ should be able to build this correctly soon (last word is Monday, 23 April). Otherwise, it needs to be built with the --edge snapcraft snap or with snapcraft from source

**Comment by jwilm** [comment]
Thanks for the patch! Is there anything we need to do other than tracking this file?

**Comment by ChrisMacNaughton** [comment]
Adding the file will allow snaps to be easily built, the snap can also be automatically built at https://build.snapcraft.io/ as an additional step (GH auth for hooks).

**Comment by jwilm** [comment]
@ChrisMacNaughton what's the command to install using snapcraft?

**Comment by ChrisMacNaughton** [comment]
`sudo snap install --edge --classic alacritty`

The --edge flag can be removed, I was publishing it to the edge channel because it's not "done" yet. Also, I'd love to pass ownership of the snap to you and help setup auto-building on Canonical's build farm ;-)

**Pull request merged**
