### PR TITLE
Feature/remember window position and size

### PR DESCRIPTION
**Pull request by brycefisher**
See discussion on https://github.com/jwilm/alacritty/issues/669

Don't merge this -- just opening this so it can be examined easily.

### CODE REVIEW

**Comment by jwilm** [comment]
Hey, thanks for the PR!

Haven't had a chance to look at the approach yet, but Isn't this something that's usually handled by macOS?

**Comment by brycefisher** [comment]
MacOS will definitely position the window somewhere by default. However, alacritty for me always opens in the exact same spot near the bottom of my screen. Is this an opt-in feature that Glutin can provide?

**Comment by jwilm** [comment]
I'm not prepared to merge this any time soon. That said, it seems like something we should provide since most macOS apps seem to "remember". My gripe with this approach is that we're adding a bunch of code to achieve this behavior whereas it seems to work out-of-the-box for most macOS applications. This suggests to me that something would need to change in winit. This might also be another reason why Alacritty should actually have a native cocoa component and just embed Alacritty as a library.

I'm going to open an issue to continue this discussion outside of a PR.

**Comment by brycefisher** [comment]
Thanks for the followup! Honestly, I felt the same about this approach. I
totally agree with closing and restarting on this feature. Seems like an
upstream feature to add most likely.

**Pull request closed without merging**
