### PR TITLE
Updates to the latest Glutin version

### PR DESCRIPTION
**Pull request by jwilm**
Alacritty is now using the latest Glutin/winit. We are temporarily on a
fork while a couple of patches get upstreamed. This branch won't be
merged until the fork is not needed.

---
This change is [Reviewable](https://reviewable.io/reviews/jwilm/alacritty/554)

### CODE REVIEW

**Comment by jwilm** [comment]
Oh, and tests don't pass yet, but the code should work at least on Linux/X11.

**Comment by auscompgeek** [comment]
Looks like the patches to winit have been upstreamed. Possibly aside from the tests, is this ready to merge?

**Comment by jwilm** [comment]
@auscompgeek not yet. There were a few regressions with winit when it was split out from Glutin and after some recent refactoring. I expect this to get wrapped up some time next week.

**Comment by igorline** [comment]
Modifier keys are not being recognized in ubuntu 16.04

```glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(KeyboardInput { scancode: 50, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }```

**Comment by jwilm** [comment]
This is on an older, broken version of Glutin/winit at this point. Will follow up soon with a new attempt.

**Pull request closed without merging**
