### PR TITLE
Implement workaround for Mesa issue

### PR DESCRIPTION
**Pull request by jwilm**
This addresses the issue where systems running Mesa drivers would be an
order of magnitude slower than other terminals. With this patch,
performance is nearly as good as with proprietary drivers. There is one
caveat where, since the cause of slowness hasn't been removed, there is
less time available for rendering on Mesa systems.

I've benchmarked this on my system (i5-3570 @ 3.4GHz, GTX 680) using
`time find /usr` with the following results:

* ~2.0 seconds average with proprietary driver
* ~2.3 seconds average with Mesa driver

cc #125

### CODE REVIEW

**Comment by Valloric** [comment]
Works great for me with this PR! I used to get `find /usr` times of 11 seconds, now it's 0.7 seconds. It also feels much snappier.

**Comment by edi9999** [comment]
It works much faster for me too ! From 60 seconds to about 6 seconds

**Comment by jonhoo** [comment]
@jwilm out of curiosity, has this performance issue been reported to upstream Mesa?

**Comment by jwilm** [comment]
@jonhoo not yet, but that would be good to do. I've got some materials that could help inform a report.

**Comment by hlieberman** [comment]
The branch massively improves performance for me.

With Mesa 13.0.2 on Debian stretch, using [Moby Dick](http://www.gutenberg.org/files/2701/2701.txt) as the corpus, in full screen, I get:

alacritty master: cat 2701.txt  0.00s user 0.04s system 0% cpu 4.292 total
alacritty #410: cat 2701.txt  0.00s user 0.03s system 65% cpu 0.043 total
gnome-terminal: cat /tmp/2701.txt  0.00s user 0.02s system 19% cpu 0.083 total

**Comment by Elronnd** [comment]
Awesome!

xterm: `cat user.txt  0.00s user 0.40s system 12% cpu 3.204 total`
vte: `cat user.txt  0.00s user 0.27s system 16% cpu 1.639 total`
urxvt: `cat user.txt 0.00s user 0.30s system 65% cpu 0.466 total`
alacritty: `cat user.txt  0.00s user 0.31s system 89% cpu 0.349 total`

An order of magnitude better than xterm, that's pretty good!

**Comment by lordtoniok** [comment]
Same here, mesa with r600g it's very fast now.

**Comment by acz13** [comment]
Alacritty is now much faster, but still slower than URxvt normally

```OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:```

**Pull request merged**
