### PR TITLE
Test old stable

### PR DESCRIPTION
**Pull request by NickeZ**
Due to #595 I propose that we build for old stable versions as well.

### CODE REVIEW

**Comment by jwilm** [comment]
This is a great addition. What do you think about only adding 1.15 though? This gets us the minimum supported version while limiting our burden on travis.

**Comment by NickeZ** [comment]
Yeah sounds reasonable, is 1.15 the oldest we compile with?

Den 1 juni 2017 18:47 skrev "Joe Wilm" <notifications@github.com>:

**Comment by jwilm** [comment]
yep, 1.15 is the oldest

**Comment by jwilm** [comment]
Thanks!

**Pull request merged**
