### PR TITLE
[WIP] Run lints as part of the build process

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Well the lints package doesn't compile. I'll have to investigate.

**Comment by NickeZ** [comment]
maybe `cargo +nightly`?

**Comment by jwilm** [comment]
Hey thanks for the effort here! I've been wanting this for a while and just haven't gotten around to it.

I think it might be best if we have some additional steps we run on the nightly build. Specifically, running clippy and the benchmark tests would be great. That should solve the issue of not compiling on stable as well.

**Comment by thedrow** [comment]
This is still work in progress.
clippy is failing to build on nightly as well :(

**Comment by jwilm** [comment]
Closing due to inactivity. Feel free to reopen if you want to keep working on this.

**Pull request closed without merging**
