### PR TITLE
Static display notification on SIGCHLD

### LINKED ISSUE #915: Quitting Vim after "alacritty -e vim" requires additional keystroke to close the terminal
If I run 

``alacritty -e vim``

And then quit right away with

``:q``

There remains a dangling Alacritty window with no text and just a cursor in the top left corner.
It persists until I move the mouse or press a key, which is a little bit annoying.
I've tested the same command with ``urxvt``, ``terminator``, ``st`` and behaviour of all seems to be the same in that they all close the terminal once ``vim`` quits.

For the record, I am writing this from Arch Linux with an i3 window manager. My server is ``X11``.

Other than that, thank you for an amazing terminal... I've been struggling to find one that takes advantage of my 144 Hz monitor, especially since I am a former FPS player and can immediately tell whether something responds to my keystrokes in 16ms or 7ms!

### LINKED ISSUE #1276: alacritty processes continue running after closing
On a fully up to date Arch Linux set up on X11 with NVIDIA proprietary driver's (396.18) and the composite extension disabled, transparency and vsync disabled (via .yml), alacritty processes continue to run and don't stop even after closing the terminal windows. My CPU cores will rise to 100% and there will be many alacritty processes running, even if you shut down the X.Org display server. I have to manually kill each alacritty process with htop for my CPU to stop maxing out at 100%.

### LINKED ISSUE #1313: Alacritty doesn't close until the first event after exiting shell
Which operating system does the issue occur on? Linux, Ubuntu 18.04

If on linux, are you using X11 or Wayland? Running Wayland with XWayland (`env WAYLAND_DISPLAY= alacritty`)

When I leave the shell with ^d or "exit", alacritty will stay alive until I do the next thing (move my mouse, click, type a character, or defocus). I'd expect it to die immediately after exiting the shell.

Screen recording of the issue: https://webmshare.com/DdYGG

glxinfo:

```console
$ glxinfo | grep OpenGL                           
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0-rc5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0-rc5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.0-rc5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

### PR DESCRIPTION
**Pull request by semaj**
Ensures that the window processor wakes up upon SIGCHLD.
Otherwise, after `exit` or `logout`, the user had to trigger
a window event before alacritty closed.

Fixes #1313.
Fixes #1276.
Fixes #915.

This may not be the best solution. It's certainly not pretty. Also, my editor is forcing rustfmt on the codebase - let me know if that's annoying. 

Relevant parts: `main.rs` :  110 - 114, `tty.rs` : 43 - 64

### CODE REVIEW

**Comment by semaj** [comment]
What are you concerned about specifically? https://docs.rs/glutin/0.16.0/glutin/struct.EventsLoopProxy.html#method.wakeup sends an `Awakened` event, which will be pushed to the window event loop's queue.

**Comment by jwilm** [comment]
Specifically about our `tty::sigchld` method. This is a POSIX signal handler, and they are notoriously difficult to work with. For more info, please see the [signal safety man page](http://man7.org/linux/man-pages/man7/signal-safety.7.html)

**Comment by semaj** [comment]
Ah, I get your point. What do you think about [handling signals via channels](https://docs.rs/chan-signal/0.3.1/chan_signal/#how-it-works)? This should have the added benefit of making the code cleaner.

**Comment by jwilm** [comment]
@semaj I'm definitely open to that sort of a solution if there's a good way to integrate it into our main loop. Ultimately, we still need to block on winit's event waiting, and there would need to be a mechanism to bridge the signal channel to the display notifier.

**Comment by semaj** [comment]
@jwilm Understood. I'll play around with it and see if there's a safer solution that doesn't incur thread overhead or busy waiting.

**Comment by chrisduerr** [comment]
Note that an event handler for POSIX signals would also be required for https://github.com/jwilm/alacritty/issues/1813 to work properly. These issues could probably both be solved with the same mechanism.

**Comment by semaj** [comment]
I revisited this today: if we assume that `display.notify()` may not be async-signal-safe, I can't think of a solution that doesn't add an extra thread, like:
1. In the signal handler, upon SIGCHLD, write to a channel or pipe
2. Spin up a new thread that `select`s on that channel or pipe and, once received, calls `display.notify()`.

I don't think this would be too heavyweight, since the new thread won't be busy-waiting.

**Comment by Hello71** [comment]
> I revisited this today: if we assume that `display.notify()` may not be async-signal-safe, I can't think of a solution that doesn't add an extra thread. For example, here's my best shot:
> 
>     1. In the signal handler, upon SIGCHLD, write to a channel or pipe
> 
>     2. Spin up a new thread that `select`s on that channel or pipe and, once received, calls `display.notify()`.
> 
> 
> I don't think this would be too heavyweight, since the new thread won't be busy-waiting.

you don't need select at all, just a blocking read. on Linux, you can use signalfd. however, that is not portable.

**Comment by rkanati** [comment]
Currently working on a fix to this that uses a self-pipe wired into the I/O event loop. I'll put up a PR sometime pretty soon.

**Comment by rkanati** [comment]
See #2114

**Comment by chrisduerr** [comment]
Thanks for your work, this has been implemented in https://github.com/jwilm/alacritty/pull/2114.

**Pull request closed without merging**
