### PR TITLE
Fix wayland clipboard integration

### PR DESCRIPTION
**Pull request by kchibisov**
What was fixed here:
- [x] Implement `gtk_primary_selection_device_manager` ( `smithay-clipborad`)
- [X] Fix race? or whatever with normal clipboard on GNOME ( `smithay-clipboard` or `alacritty` )
- [ ] Clipboard dies over time on sway/probably GNOME (`smithay-clipboard`)

Initial attempt to fix clipboard on wayland.

Fixes: #2574

### CODE REVIEW

**Comment by kchibisov** [comment]
I've added implementation of `gtk-primary-selection`, for now it's in my fork, but both clipboards are working fine for me on GNOME + wayland.

The last issue I have here, is that clipboard die, when tty switch occurs(not always dies though), however I don't think this remaining issue should block merging this PR, since we've already has some problems with tty switching.

**Comment by trimental** [comment]
smithay-clipboard v0.3.4 has been released with your gtk fallback implementation, good work

**Comment by kchibisov** [comment]
@trimental I've noticed, thx for your help.

>  The last issue I have here, is that clipboard dies, when tty switch occurs(not always dies though), however I don't think this remaining issue should block merging this PR, since we've already has some problems with tty switching.

@trimental , What do you think about this issue though? Asking here for now, probably move this question to Matrix.

**Comment by nixpulvis** [comment]
@kchibisov FWIW, we are also pretty active in the #alacritty Freenode channel too.

**Comment by kchibisov** [comment]
@nixpulvis I'm aware of it, but the last issue is likely with Smithay's stuff, rather then alacritty's, so asking there would make much more sense in my opinion (I'm about smithay chatroom on matrix).

P.s.
@nixpulvis, I'm too young for IRC stuff though, but I'll investigate in solving this problem ;- ). I've already tried that in the past, but I've wiped `weechat` during storage upgrades on my PC.

**Comment by trimental** [comment]
@kchibisov mm I’m unsure about the tty switching, there are people on the smithay matrix channel with more general wayland knowledge then me that may have an idea, although I’ll hopefully be able to investigate over the next few days.

About the IRC, you can use matrix IRC bridges to connect without needing an IRC client, I think you need to connect to 	`#freenode_#alacritty:matrix.org`

**Comment by kchibisov** [comment]
@chrisduerr I think this PR is ready for a review.

There is one more issue with wayland clipboard, but it wasn't the subject in #2574 and I guess only I noticed that issue. I'm switching to X11 sessions to test alacritty's cursor stuff, so that was the first time I've experienced some problems with clipboard, but it doesn't die over time as I've initially stated, since I had 10+ terminals running for more than 24 hours+ in a row and everything was fine with clipboards, unless I've decided to switch tty.

**Comment by pschyska** [comment]
@kchibisov I've also finally got around testing your changes. Seems to work perfectly!

I ran alacritty about 20 times and couldn't make the clipboard misbehave. Additionally, primary selection worked -- in true Heisenbug fashion, the primary selection never worked for me as well anymore on the stable version :smile:, which makes more sense due to the interface change discussed earlier.
Either I tested incorrectly, or something in Gnome changed recently (I switched to I3 because of the clipboard issues).

Thanks a lot!

**Comment by kchibisov** [comment]
@chrisduerr Looks fine. Just push "Fix clippy issues" and "my Fix" in a separate commits.

**Comment by chrisduerr** [comment]
I've merged this into master manually.

**Pull request closed without merging**
