### PR TITLE
Fix tabulation rendering

### PR DESCRIPTION
**Pull request by shmatov**
Hey,

I've found two problems with tabulation rendering:
1. tabulation grid is filled incorrectly, it has 8 false elements on the head of the vector. https://github.com/jwilm/alacritty/commit/7906c8125a81199b097cf74b7d156673871d8149
2. there is a case when no empty columns will be rendered for `\t`. https://github.com/jwilm/alacritty/commit/37ad49476f0aeb434557f386dedc945df28e8610

Fixes: https://github.com/jwilm/alacritty/issues/142

A couple of screenshots

Before:
echo

After:
fixed echo

Before:
ls

After:
fixed ls

There is a problem with `tab_bg_highlight` test, but it seems that we just should update [grid.json](https://github.com/jwilm/alacritty/blob/master/tests/ref/tab_bg_highlight/grid.json). Is there any way to do it automatically?

### CODE REVIEW

**Comment by jwilm** [comment]
We can just regenerate the test. It's not checking tab spacing thankfully, but it will serve as a regression for your patch as well in the future :). I'll push a commit updating the test shortly.

**Comment by jwilm** [comment]
I think we've still got a bug with the tab handling. If I only put 7 `a` and a `\t`, I would expect the tab to only occupy one space. Instead, it's not until there's only 6 characters that we see the extra tabstop go away.

image

Do you fancy looking into that as well?

**Comment by shmatov** [comment]
@jwilm I've found an issue with tab width in my previous commits, also that's was the reason of the broken test. Sorry for that. Here is a better fix for tabulation rendering: https://github.com/jwilm/alacritty/pull/466/commits/611589a28b0db5bab8db3f039a3ccbb38d122f33

**Comment by jwilm** [comment]
While I like the simplicity of this solution, it breaks the ability for a terminal program to set custom tab stops. The command is [HTS (horizontal tab set)](http://vt100.net/docs/vt100-ug/chapter3.html#HTS), and there's another one for clearing. We don't actually implement either of these right now, but the Vec removed in the latest commit would be necessary to support it.

**Comment by shmatov** [comment]
@jwilm wow, I didn't know about HTS/TBC, thanks! It seems that this commit (https://github.com/jwilm/alacritty/pull/466/commits/1b5a5fa8c18b9657a6751dcb2f1d901a042bf31c) should fix the issue. At least in my test case it looks like the screenshot above.

**Comment by jwilm** [comment]
This looks great--both the example and the code. I've added a ref test using the provided tab chart. Will merge once travis goes green.

**Comment by jwilm** [comment]
Thanks again @shmatov

**Pull request merged**
