### PR TITLE
fix for  #1435

### PR DESCRIPTION
**Pull request by elfranne**
see https://github.com/jwilm/alacritty/issues/1435 for more details

### CODE REVIEW

**Comment by chrisduerr** [comment]
See #1413, this should work with the latest stable version of Rust being up-to-date.

**Comment by jedahan** [comment]
Maybe a comment in the file was be helpful

**Comment by elfranne** [comment]
I ll close this and update the docs to include some more info

**Comment by chrisduerr** [comment]
I'm not sure if more information is necessary, upgrading your toolchain to the latest version of Rust should be a straight-forward step when a `Cargo.toml` field isn't recognized, after all automatic CI is building Alacritty on every commit, so it's unlikely that there is an actual error in the toml which prevents building.

And there is documentation for all settings in the `Cargo.toml` online, I don't think this is some kind of hidden feature. Having `debug = 1` isn't much different from having `lto = true` I'd say, the only difference is how far back you have to go until Rust doesn't recognize the compiler option anymore.

**Pull request closed without merging**
