### PR TITLE
Use just instead of make

### PR DESCRIPTION
**Pull request by casey**
This PR:

- Changes the makefile which builds the MacOS app package into a justfile
- Changes instances of `osx` into `macos`, since that seems to be the new name
- Adds a `macos-` prefix to the recipe names so that other recipes can be added without conflicting

Just is a command runner which avoids the complexity and idiosyncrasies of make while retaining the concise syntax: https://github.com/casey/just

This introduces a dependency for building the mac app, so I'll understand if you don't want to merge it.

If you like the idea of trying out just but don't want to introduce it as a dependency for building the mac app, I can close this PR and open one which has a simple justfile and doesn't modify the current makefile.

Some advantages of just:

- Variables are single-assignment and order-independent, which makes them very easy to reason about and avoids the `=` vs `:=` duality of make
- Undefined variables generate an error instead of expanding into the empty string
- Both runtime and compile time messages are *much* better than make's. They are colored, give precise information about what went wrong, and highlight the line in question
- Close enough to makefile syntax that vim and emacs syntax highlighting work well out of the box
- Does not depend on make, so behavior is correct regardless of the system-provided make
- Is not a build system, so does not need `.PHONY` targets or other hacks
- Written in rust, installs through cargo
- Supports doc-comments, listing recipes, listing evaluated variables, and other helpful command line options
- Like git, just can be invoked in any subdirectory of the project
- Tabs or spaces both work for indentation, as long as they are consistent within a single recipe

It's very good as a place to store frequently run project-specific commands, both for yourself and collaborators. For example, different ways of running tests, different build configurations, running with a debugger, fuzz testing, running kcov, etc. Basically, anything you currently reverse search your shell history to find. See [here](https://github.com/ssokolow/rust-cli-boilerplate/blob/master/justfile) and [here](https://github.com/casey/boilerplate/blob/master/justfile) for examples.

### CODE REVIEW

**Comment by kiljacken** [comment]
Why not "just" (hehe) use a shell script at this point? I'd assume the point of using make is that it's easily available on most platforms.

**Comment by casey** [comment]
I agree that make is nice because it's easily available. Just has a lot of advantages over a shell script, however. The error messages are good, the behavior is unsurprising, and the format is succinct.

I think for alacritty, the main benefit is probably being able to add more commands in the future. And, as stated, it might not be worth it to introduce a dependency just for building the macos app, in which case it might still be worth adding a justfile with commonly run commands.

**Comment by aoeu** [comment]
I found this pull-request while searching to see if anyone else has been working on furthering Unicode support.

I use `just` nearly as much as `cd` or `ls` while doing my day-to-day work, and `alacritty` has become my de-facto terminal emulator.

I would both use and help maintain the `justfile` it if this pull-request was merged.

Maybe it would be possible to keep both the `makefile` and add the `justfile` for those of us that would get great use from it?

**Comment by jwilm** [comment]
@casey Thanks for the PR! I had never heard of Just until reading here. Seems like it does a lot of things right where Make dropped the ball.

> This introduces a dependency for building the mac app, so I'll understand if you don't want to merge it.

Definitely not thrilled about the idea of an extra dependency that's not universally available. Having to add extra instructions for anyone building from source is a non-starter for me. Sorry :(

> Maybe it would be possible to keep both the makefile and add the justfile for those of us that would get great use from it?

Then they would both need to be maintained, and they would undoubtedly get out of sync.

Thanks again for the PR and discussion here. Going to keep the Makefile for now.

**Pull request closed without merging**
