### PR TITLE
Blinking Cursor

### PR DESCRIPTION
**Pull request by jwilm**
This is very much a WIP for blinking cursor. I'm not very fond of the implementation at the moment, and I may end up scrapping this and taking a different approach.

## Implementation Status

- [x] Cursor blinks
- [ ] Cursor blinks only when window is focused
- [ ] Cursor blink should be disabled for a second after keyboard input

### CODE REVIEW

**Comment by jwilm** [comment]
Oops, broke this with a rebase. Worked on top of #650.

**Comment by DarkDefender** [comment]
I'm sure you might already know this, but the current code does not respect the blink/noblink versions of the cursor changing codes like:
```
printf "\x1b[3 q" #underline, blink
printf "\x1b[4 q" #underline, noblink
```

**Comment by unphased** [comment]
@jwilm I think that it may be cool in addition to adding the standard blinking capability to allow users to configure more "modern" ways to display a blinking cursor. I was thinking of something that animates and fades, maybe even with a subtle CRT-like bloom visual effect. Do you think that this would be cool, or would it fly in the face of our minimalistic principles?

**Comment by jwilm** [comment]
Closing this PR since it's not anywhere near ready to land. The branch will remain available on the repo for now.

**Comment by cata0309** [comment]
@jwilm any news about the blinking cursor? (I am really not into opening issues that would be closed as duplicates!)

**Comment by chrisduerr** [comment]
@cata0309 If you're interested about updates, please subscribe to https://github.com/alacritty/alacritty/issues/302.

As long as that issue isn't updated, there has not been any progress.

**Pull request closed without merging**
