### PR TITLE
Make the macOS bundle compatible osx 10.12

### PR DESCRIPTION
**Pull request by Carreau**
On macOS 10.12.6 (as far as I can test), running `make app` creates a
bundle that refuses to start (it complain application is only compatible
with more recent versions of macOS. The binary works great when running
it directly.

As far as I can tell this fixes the issue and the bundle works great
(despite the other issues reported for login shell, but I guess that's
another story).

I'm going to _assume_ that targeting 10.11 or lower would also work.
I don't know what effect this have on the final binary and whether this
removed  some optimisation. Maybe that could be conditionally setup
depending on the version of macOS this is built on?

### CODE REVIEW

**Comment by chrisduerr** [comment]
Thanks for this PR!

Since the Alacritty build instructions for macOS include `make`, I wonder if the source code is the right place for this. It would probably be possible to check the macOS version from the makefile and then set the environment variable to override it. That should also take care of any potential optimizations that might be different between macOS versions.

**Comment by Carreau** [comment]
I'll have a look to see if that work, and tryin to detect the current macos version if possible.

As a side (related) question, have you looked in [cargo-bundle](https://github.com/burtonageo/cargo-bundle) ? I initially got that to work by side-stepping `make app`, in which case moving the logic to Make (if we get rid of it later) is counter productive. 

I'm also quite new to rust, so may be completely missing some points.

**Comment by chrisduerr** [comment]
I'm not sure about cargo-bundle. There are a few difficulties I can see with this though. I'm not sure if we'd still have control over the `.app` file for example, which is important. It would also require installing an extra tool, `make` itself is already quite common compared to that.

We're already making use of `cargo-deb`, but even that is more to fill in a gap, rather than using it as a primary form of distribution. Handing this off would mean giving control to someone else. And I'm not sure if outsourcing macOS build support would make anything better, or if it would just introduce additional points of failure.

That said, even if the logic is moved to make now, it shouldn't be an issue to change things later, rather than making a commitment to a change now, which might never happen.

**Comment by Carreau** [comment]
> I'm not sure if we'd still have control over the `.app` file for example, which is important.

Can you develop on that ? The alacritty bundle seem pretty bare... what "control" do you wish to have ? 

I was more thinking in the sens that the less you have to do the better, and that cargo-bundle is offloading thinking about packaging... but up to you. 

I've push a change that move the detection of MacOS version to the Makefile. There is one drawback though. The following will not work:

```
 ~/dev/alacritty[osx2 ✓] $ cargo build --release
   Compiling alacritty v0.2.0 (file:///Users/bussonniermatthias/dev/alacritty)
    Finished release [optimized + debuginfo] target(s) in 2m 24s

 ~/dev/alacritty[osx2 ✓] $ make app
MACOSX_DEPLOYMENT_TARGET=10.12.6
cargo build --release
    Finished release [optimized + debuginfo] target(s) in 0.24s
Created 'Alacritty.app' in 'target/release/osx'
```

Indeed, Cargo does not see that the release need to be rebuilt because of the change in environment variable. Which it does if the logic is in `build.rs`, and the .app bundle appear as invalid.

**Comment by chrisduerr** [comment]
Last changes are looking good. I'd like to make sure that this still works on platforms other than 10.12 though. So if anyone can test that, I'd appreciate it.

**Comment by sodiumjoe** [comment]
tested on macOS 10.13, works great!

**Comment by Carreau** [comment]
Thanks @sodiumjoe !

**Comment by Carreau** [comment]
Thanks for you guidance and accepting this PR.

**Pull request merged**
