### PR TITLE
Fix locale_id for older versions of OS X (<= 10.11)

### PR DESCRIPTION
**Pull request by bradfordboyle**
Fixes jwilm/alacritty#1326

### CODE REVIEW

**Comment by chrisduerr** [comment]
It's probably best to just summon the might MacOS wizard @sodiumjoe, he's probably able to help out here. :)

I suppose that this might an issue with alacritty's targeted MacOS version. I believe there hasn't been made any final decision which versions should be supported, other than at least 10.11. So it's possible that everything below 10.11 just hasn't been considered.

**Comment by sodiumjoe** [comment]
😬 I'll take a look when I get a chance, probably in the next few days

**Comment by sodiumjoe** [comment]
This actually looks right to me. I missed [this line](https://github.com/jwilm/alacritty/pull/1087/files#diff-5ffadea12561d6964b05ac2a0b8e388fL33) when I added the fallback to localeIdentifier.

I just tested this branch, and it works fine for 10.13, which is expected since that takes the other conditional branch. I'm surprised this didn't come up earlier.

**Comment by loothoader** [comment]
I’m not sure how relieve my it is now. But it had come up once. Late last Sept when I reinstalled a 5yr old mini from its carbon copy.It managed to lock mini’s firmware in one go.

**Pull request merged**
