### PR TITLE
Assure that newlines are in selections

### PR DESCRIPTION
**Pull request by DSpeckhals**
When a selection was made, the last line of the selection did not include a new line character when the line ending was selected. This would occur if only one line was selected; if multiple lines were selected, only the final line did not include a newline.

This commit updates the `string_from_selection` function to attempt to append a newline character in all places where they are suitable. Because of the simplification of newline insertion, several trait implementations were removed.

This fixes the first part of #432.

### CODE REVIEW

**Comment by nixpulvis** [comment]
I'm digging into this a little bit right now, trying to add a test. First thing that jumps out at me (not directly related to this PR) is that there's no good way to generate a `Selection` of multiple lines. I'm still learning this codebase, but I was hoping to simply modify the `line_selection_works` test with a `Selection` that spans two lines.

Thoughts?

**Comment by nixpulvis** [comment]
The test I have at the moment is

```rust
    #[test]
    fn line_selection_works() {
        let size = SizeInfo {
            width: 21.0,
            height: 51.0,
            cell_width: 3.0,
            cell_height: 3.0,
            padding_x: 0.0,
            padding_y: 0.0,
        };
        let mut term = Term::new(&Default::default(), size);
        let mut grid: Grid<Cell> = Grid::new(Line(3), Column(5), &Cell::default());
        for i in 0..5 {
            grid[Line(0)][Column(i)].c = 'a';
            grid[Line(1)][Column(i)].c = 'b';
        }

        mem::swap(&mut term.grid, &mut grid);

        let mut selection = Selection::lines(Point { line: Line(0), col: Column(3) });
        // NOTE: The `Side` here is irrelevent...
        selection.update(Point { line: Line(1), col: Column(3) }, Side::Right);
        match selection.to_span(&term) {
            Some(span) => assert_eq!(term.string_from_selection(&span), "aaaaa\nbbbbb\n"),
            _ => ()
        }
    }
```

I think there's a lot of room for testing improvement here though.

**Comment by nixpulvis** [comment]
I think as part of this we should make it so when selecting past the last character of a line the **whole** rest of the line gets highlighted all at once, thus indicating the newline will be copied. This mirrors some other terminals like `urxvt`.

In pictures:
deepinscreenshot_select-area_20171118153443
deepinscreenshot_select-area_20171118153519

**Comment by jwilm** [comment]
This simplifies things nicely. Thanks for the PR!

**Pull request merged**
