### PR TITLE
Added a freedesktop.org desktop entry and instructions for using it to README.md

### PR DESCRIPTION
**Pull request by amikhalev**

### CODE REVIEW

**Comment by NickeZ** [comment]
If you do `cargo install` it will get installed into path, if you have something like `source .cargo/env` in your init. Maybe that should be the suggested way to install the binary instead?

**Comment by jwilm** [comment]
Thanks @amikhalev

**Comment by amikhalev** [comment]
@NickeZ The issue is that most DMs don't source your init when looking up applications in $PATH.

**Comment by NickeZ** [comment]
@amikhalev I guess you mean the latest Wayland issue. I would say that before wayland `.profile` or `.bash_profile` or equivalent was always sourced when logging in. https://lwn.net/Articles/709769/

I installed alacritty with cargo install and it works as expected.

**Pull request merged**
