### PR TITLE
Added fullscreen option to config

### LINKED ISSUE #38: Fullscreen support
Config should support something like `fullscreen: true` so that alacritty starts fullscreen/maximized.

### PR DESCRIPTION
**Pull request by mheuser**
resolves #38 - at least for macos. Not tested with other platforms.

### CODE REVIEW

**Comment by mheuser** [comment]
I will try to get another monitor and compare the behaviour against iterm fullscreen startup (which i almost deleted since i found this great emulator today!).

Another option is to define a monitor id (string) or enumerator in the config where to start in fullscreen - but more for a stationary setup.

I will give feedback after i found another monitor somewhere.

**Comment by Thomasdezeeuw** [comment]
@mheuser I've got multiple monitors and macOS, what exactly needs to be tested?

**Comment by mheuser** [comment]
@Thomasdezeeuw That Iam not so sure as well :-) here what I did

Setup: macOS with 2 Monitors, alacritty with fullscreen start enabled, iterm2 with fullscreen start enabled.

1. Primary monitor active - Start Iterm2 via Spotlight Search - Iterm2 starts in fullscreen on the primary monitor.

2. Primary monitor active - Start alacritty via Spotlight Search - alacritty starts in fullscreen on the primary monitor.

3. Secondary monitor active - Start Iterm2 via Spotlight Search - Iterm2 starts in fullscreen on the secondary monitor.

4. Secondary monitor active - Start alacritty via Spotlight Search - alacritty does not start.

5. Secondary monitor active - Start alacritty via shell (alacritty started on primary then moved to secondary or iterm) - alacritty starts in fullscreen on the primary monitor.

Seems like it should use the active window. Will look into that - but can't make promisses.

**Comment by Thomasdezeeuw** [comment]
@mheuser I've enable the fullscreen option and tried to following:

- Opened Alacritty on the primary monitor: opened in fullscreen, seems OK.
- Opened Alacritty on secondary monitor: got a panic in winit:
```
thread 'main' panicked at 'not yet implemented', /Users/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/macos/window.rs:657:21
stack backtrace:
   0:        0x102390cc3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::ha5390fdff9464f8a
   1:        0x102393824 - std::panicking::default_hook::{{closure}}::h77e524c36212763b
   2:        0x102392430 - std::panicking::rust_panic_with_hook::h0fc7642366254cdd
   3:        0x102299347 - std::panicking::begin_panic::h0e4a98e345aa6a62
   4:        0x102292dd8 - winit::platform::platform::window::Window2::new::h5fac80c564335aa5
   5:        0x10228b09c - glutin::GlWindow::new::ha92ee07e0f20b23e
   6:        0x10224f955 - alacritty::display::Display::new::h31eb9e49583e54bc
   7:        0x1023dc711 - alacritty::main::hf70bf2b591effbe1
   8:        0x1023b2c65 - std::rt::lang_start::{{closure}}::h5ceafaaa8185b2a1
   9:        0x1023d9af4 - main
```

**Comment by chrisduerr** [comment]
Note that there is a PR for maximizing rather than fullscreen here: #1273.

I'm not sure how other platforms handle this, but on Linux/Windows I would assume that maximizing is desired rather than fullscreen.

This does not have the issue with selecting the correct display, so if it does everything that is needed, it should be fine.

If true fullscreen mode is desired, it is necessary that the remaining problems with this PR are resolved.

**Comment by chrisduerr** [comment]
It seems like https://github.com/jwilm/alacritty/pull/1823 is a better choice moving forward. Since it maximizes the window instead of putting it into fullscreen mode, it's not necessary to specify the monitor either.

As far as I'm concerned, with a maximized option it shouldn't be necessary to fullscreen Alacritty anymore, since based on my experience you'd want to maximize a terminal emulator on startup rather than actually putting it into fullscreen. However I have only limited experience with platforms besides Linux, so if this is still desired, please let me know.

**Comment by tbo** [comment]
@chrisduerr I have to disagree with you on that one. At least on MacOS it is much more common to use fullscreen applications. The default Mac OS window decorations only offer fullscreen by default. This includes Alacritty for Mac OS.

**Comment by chrisduerr** [comment]
Hmm that's very interesting. I suspect that might be because the dock at the bottom is so huge in macOS?

The preferred behavior would be to make the `start_maximized` setting maximize on linux and windows, but fullscreen on macOS then I guess. That way we wouldn't have to clutter the configuration file with two different settings, when only one would be used.

The issue with querying which monitor it should be launched on is still present though even when doing that. I'm open to including this feature if someone finds a nice way to query that using winit/glutin. However I think that re-opening this PR contributes little to that, since building on the maximized PR makes more sense.

So my recommended strategy would be to go for a follow-up PR for anyone who's interested in trying to figure out how to use `start_fullscreen` with the right monitor, instead of taking the approach of this PR using `set_fullscreen` call which will cause flickering at startup.

**Pull request closed without merging**
