### PR TITLE
Add background image

### PR DESCRIPTION
**Pull request by tamamu**
Add background image with a new configuration option `background_image`.
If you would like to try on it, add a new row in your `alacritty.yml` to set the path to the image, like as:
```yaml
background_image: /home/tamamu/Pictures/background.jpg
```
PNG is also ok.

There is a certain demand of this feature.
See #565

Screenshot from 2019-09-15 01-24-06

### CODE REVIEW

**Comment by chrisduerr** [comment]
Thanks for the pull request, however as mentioned in #565, I do not think this aligns with Alacritty's goals. While it's always nice to have options and customization, I do not think it's worth the maintenance burden and overhead.

**Comment by nixpulvis** [comment]
Thanks for your interest in Alacritty, and for taking the time to write this feature.

Some of us have talked a bit about this (before, and now again), and we're leaning towards not adding this feature to mainline Alacritty. I know that there some users who would like to see this added, but it's also not "make it or break it" kind of thing in our eyes. Alacritty is a pretty minimal terminal emulator, and we don't always add things just because we can.

Our concerns are specifically:

1. Feature bloat (what next, video backgrounds?)
2. Extra maintenance burden
3. Potential availability via the transparency feature

I know not everyone will agree with this decision, but we believe it's in the best interest of the project as a whole. I hope you understand.

I do encourage you to maintain this branch and use it as you need if you so desire.

**Comment by aswinpajayan** [comment]
Is there a feature branch with this modification

**Comment by aswinpajayan** [comment]
This feature would have been really nice

**Comment by aswinpajayan** [comment]
can you give build instructions

**Comment by aswinpajayan** [comment]
i was not able to get the feature when build from the sources

**Comment by tamamu** [comment]
@aswinpajayan 

The branch is no longer maintained but you should be able to build it as below.

```
git clone -b background-image https://github.com/tamamu/alacritty; cd alacritty
cargo build --release
```

then edit your alacritty.yml to set the path to the background image.

Thanks!

**Comment by casserlyprogramming** [comment]
>  did not show a significant amount of interest for this feature.

The 29 comments on the original issue, a follow up issue and this PR isn't enough interest from the community?

**Comment by chrisduerr** [comment]
29 comments isn't a lot, no. And you conveniently left out the part where I mentioned that the lack of interest is just an additional hurdle on top of not fitting in with Alacritty's goals.

**Pull request closed without merging**
