### PR TITLE
Add tabs on Windows to FAQ per #1981

### PR DESCRIPTION
**Pull request by mikemaccana**

### CODE REVIEW

**Comment by chrisduerr** [comment]
I have personally never used Groupy and I do not think it's a good idea to advertise third party applications in this fashion. It's up to the user to decide which application he wants to use to make up for the lacking Windows support for tabs and I don't think there's any need for guidance here.

**Comment by mikemaccana** [comment]
It's not advertising - there's 0 other apps that can do this (I've researched the topic fairly extensively).

**Comment by mikemaccana** [comment]
@chrisduerr Would you accept the PR if either:

 - A We explicitly mention Groupy is not endorsed by thee Alacritty developers
 - B We didn't mention Groupy by name but said 'third party applications that add tabs to Windows' 

?

**Comment by mikemaccana** [comment]
Looks like you can't update a PR once it's been closed, so this became #1984

**Comment by chrisduerr** [comment]
> Looks like you can't update a PR once it's been closed, so this became #1984 

I am able to re-open closed PRs. So please don't keep re-opening closed PRs which have been closed for a good reason.

I do not see why Alacritty would explicitly document the lack of tabs *again* in the faq, after it is already documented that some advanced features like tabs and splits are not supported.

There is nothing that separates tabs from other advanced features and it makes little sense to document every unsupported feature separately in the FAQ section. As the name might indicate, the FAQ section is about frequently asked questions which are unanswered in the rest of the readme. This is not the case for tabs.

**Pull request closed without merging**
