### PR TITLE
[WIP] copypasta x11 support use xcb

### PR DESCRIPTION
**Pull request by quininer**
1. Should add an `x11` feature to support non-Linux OS(like freebsd) ?
2. Should support Windows?
3. Should add `Clear` trait?

### CODE REVIEW

**Comment by jwilm** [comment]
Is there any advantage to using libxcb versus normal X APIs? `xclip` is obviously not ideal, but is `xcb` the right way to do this?

> 1

Yes, but it would need testing

> 2

Yes, but not a priority right now

> 3

Doesn't seem important, but correct me if I'm wrong.

**Comment by quininer** [comment]
@jwilm Qt uses xcb to implement the clipboard on x11, which I think is right.

> 3
It may not be important for the terminal emulator, but it should not be missing as a complete clipboard library.

I see somebody [proposing](https://github.com/servo/servo/issues/12805#issuecomment-271052079) to use copypasta on servo.

**Comment by jwilm** [comment]
> Qt uses xcb to implement the clipboard on x11, which I think is right.

Good enough for me

> It may not be important for the terminal emulator, but it should not be missing as a complete clipboard library.

Makes sense. I'd rather not have features that nobody uses--someone has to maintain the code. If it's simple, then sure it seems fine.

**Comment by quininer** [comment]
I found an interesting [library](https://github.com/jeandudey/xrb-rs). when I'm ready, I will open a new PR.

**Pull request closed without merging**
