### PR TITLE
Rust 2018, NLL fixes

### PR DESCRIPTION
**Pull request by jwilm**
This updates Alacritty to Rust 2018 while fixing old workarounds for lack of NLLs. Almost all `// borrowck` commens have been resolved except for two instances of overlapping mutable borrows not quite covered by the initial NLL support.

### CODE REVIEW

**Comment by chrisduerr** [comment]
IIRC the Rust 2018 edition shouldn't require `extern crate` anymore, right? That should probably be removed too.

I think there was another rustfix command for idiomatic Rust 2018 code vs correct Rust 2018 code, though I'd have to look that up myself.

**Comment by jwilm** [comment]
WRT extern crate, the cargo —fix command didn’t change it. I’m indifferent on whether it’s included or not, but I guess if it’s considered idiomatic not to have it, we should remove those too.

**Comment by chrisduerr** [comment]
@jwilm Looking at `cargo fix --help`, there seems to be `cargo fix --edition` and `cargo fix --edition-idioms`. I'd try running that and just checking out what rustfix does, I think that should resolve the extern crate thing.

**Comment by jwilm** [comment]
Ah, I didn't run the `-idioms` variation

**Comment by chrisduerr** [comment]
Looking at the output of the edition idioms, it looks like there's **a lot** of work to be done. Instead of just simply running it and everything's good to do.

I'd propose just working on these separately. This would give people the chance to fix one idiom issue at a time, instead of having to do all at the same time.

**Comment by chrisduerr** [comment]
I've managed to apply the fixes running `cargo fix --edition-idioms --broken-code` which is supposed to break a lot of stuff but it worked out great for Alacritty.

I've had to manually touch up some changes, but after doing a full review of the new changes, everything's looking good.

Some `#[macro_use] extern crate` and `#[cfg(not(Linux))] extern crate` imports are still present. I'd remove those myself, but I don't want to rely on travis to provide me feedback about the success of my changes, so I'll leave that to Windows/macOS users.

**Comment by neersighted** [comment]
I just wanted to note that `macro_use` should no longer be necessary as macros can be imported using `use`.

**Comment by chrisduerr** [comment]
@neersighted I'm aware of that, however my attempt to remove these lead to unnecessarily much work, since especially serde macros are used everywhere.

**Comment by neersighted** [comment]
Fair enough. That can always be cleaned up later.

**Comment by chrisduerr** [comment]
I've decided to remove some more `extern crate` imports which import macros. Though `log` and `serde` are still untouched in the `src/lib.rs`.

I think that should be plenty for this PR, so once CI is finished this can be merged. Further changes can be submitted in separate PRs, which will make things much easier since rebasing this PR would be a major pain.

**Pull request merged**
