### PR TITLE
Refactor populate cursor, fix-wide-cursor

### PR DESCRIPTION
**Pull request by OliverUv**
This refactors the populate cursor functions. It also applies the functional part of the fix-wide-cursor branch (i.e. does not apply the debug printlines.)

Tested with all three cursor modes. Tested with wide characters `ａｓｄｆ`.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for the PR  @OliverUv 

Something is slightly broken here. Here's underline cursor on this PR. It's correct width, but char is hidden.
image

And here it is on master.
image

**Comment by OliverUv** [comment]
So, with this new commit the behavior is back to what it was before my branch.

However, I feel like it is/might be incorrect behavior in one way: the second cursor character is not printed when over wide characters. I'm not sure why this happens.

I've looked a bit at the rendering code. Doesn't seem to be doing any overwriting when adding new cells to the rendering buffer, unless something such happens during instancing that I'm not aware of.

I believe this is the first time in the codebase that RenderableCellsIter::cursor_cells contains more than 2 items, so perhaps there is some error in it's next method. Haven't spotted anything yet, though.

**Comment by jwilm** [comment]
It looks like there might be a bug with the ArrayVec crate where you need to request one more capacity than is needed. I updated this with master and will merge shortly.

**Comment by OliverUv** [comment]
:clap:

**Pull request merged**
