### PR TITLE
Bump version number to 0.2.0

### LINKED ISSUE #1240: Could Alacritty start tagging versions?
Even if you don't feel "worthy" of a 1.0 for some reason, the reality is that people are using and packaging alacritty, and it would be reassuring if the commits packagers are checking in as the *current version of alacritty* into packaging systems aren't just their best guesses for okay cut points.

Even if the version is 0.x, would it be possible to start tagging versions occasionally?

My horse in this race is [getting the Void Linux alacritty package updated](https://github.com/voidlinux/void-packages/pull/11390), but I'm sure other distros' packagers would love to see versions tagged too.

### LINKED ISSUE #1534: Add CHANGELOG
Before shipping scrollback, add a CHANGELOG file. We don't need to worry about backdating for everything that's happened in the last 21 months ;).

### PR DESCRIPTION
**Pull request by chrisduerr**
Since the Scrollback branch introduces some major changes, this bumps
the version number from 0.1.0 to 0.2.0.

The versions of Alacritty have not been updated regularly to this point,
so the scrollback branch is a good point in time to start updating
Alacritty's version on a regular basis.

Further changes to the readme, like dropping the 'alpha' status and
updating it to 'beta' could also be introduced with this branch. This
way there will be a clean cut which updates everything as soon as
scrollback is merged.

Building versions is another thing which would be a good thing to start
reasonably quickly. However starting this on the main branch after
scrollback has been merged seems like a more reliable way to move
forward.

@jwilm Please let me know if you would prefer going a different way
about this. But it seems like the best point in time to make this change.

This fixes #1534.
This fixes #1240.

### CODE REVIEW

**Comment by jwilm** [comment]
Feel free to merge this; opening another issue to add a bit of a changelog before we ship the scrollback project.

**Comment by chrisduerr** [comment]
I've added a `CHANGELOG` file and added a few of the changes that have been introduced with the scrollback PR. This should give the `0.2.0` release a bit of content so users will already know what they can expect from the release.

This is the commit message for a full description:
<details>

```
A CHANGELOG file has been added to offer a bit more transparency over
which features have been changed, added and potentially removed in
Alacritty.

There are various formats available for the CHANGELOG file but the most
common and sensible one seems to be the one defined by
https://keepachangelog.com/en/1.0.0. Following the template proposed by
this it should be possible to create a clear CHANGELOG which makes it
simple for new contributors to figure out exactly which formatting
should be used for it.

Since there have been quite a few changes to Alacritty already, not all
changes have been added to the changelog. However a few entries have
been ported just to give a bit of an example what the format should look
like. This also helps with the 0.2.0 version since it will not be
completely empty in the changelog.

This fixes #1534.
```
</details>

I'll keep this PR open for now because of the changes I've introduced @jwilm.  If you want to add any more entries to the CHANGELOG which are significant to the 0.2.0 release you should be able to just push them to my branch.

**Comment by chrisduerr** [comment]
Since there was a new commit on the latest master, I've also rebased on top of that to keep the scrollback branch up-to-date.

**Comment by nixpulvis** [comment]
@chrisduerr, looks more like a merge to me. Also wouldn't this be the sort of thing to do directly into the scrollback branch? Not that it really matters.

**Comment by chrisduerr** [comment]
Oh yeah it's a merge, since that's less likely to cause any issues at this point (at least in my experience).

And I don't really want to push directly to any branches, so I'd rather do it in a PR. Now if it should be done in this PR or a different one, that's another question. But I thought this would be a good place to add some finishing touches to scrollback.

**Comment by nixpulvis** [comment]
Fair enough.

**Comment by FFY00** [comment]
I am not really involved in this project but let me just leave a note. Merge commits usually make the history much more ugly and complicated. This is not the case here as it's a really simple conflict (rebasing would do just as fine) but for more complex things it is something we usually don't want to do, especially for big projects.

**Comment by chrisduerr** [comment]
@FFY00 I completely agree with that sentiment and I think usually a rebase is a lot nicer than a merge. However with a change like that which basically completely rewrites large parts of the code and is developed in parallel to another branch, I find that the increased ugliness isn't too much of a price to pay for the less error-prone process.

When using rebase on two branches developed in parallel it's easy to lose track of which change is the correct one to 'pick', especially since rebase often prompts multiple times during the process and the decision which one should be picked might vary based on the intermediate steps that come up.

So with pretty much every other PR I'd go for rebase without a question. But after being lucky enough to catch a rebase issue before it was merged into scrollback, I'm staying a bit wary of using rebase on this PR.

**Pull request merged**
