### PR TITLE
Icon for linux desktop entry

### PR DESCRIPTION
**Pull request by enizor**
Uses the icon from #285 converted to PNG (a SVG might be better if @net could make one).

I put the icon in `assets` but there might be a better location.

How it looks like on Cinnamon desktop: 
alacritty_mint

### CODE REVIEW

**Comment by net** [comment]
I brought this up in #856 but I think it went unnoticed:

Personally, I’m more of a fan of the blue flame variant.



I’ll make a PR with an SVG and rendered PNG later when I have a bit more time.

**Comment by k0nserv** [comment]
FYI: The macOS icons is already done in https://github.com/jwilm/alacritty/pull/856. I used the icns that you posted as part of the thread @net

**Comment by enizor** [comment]
It was your PR that made me realize of the existence of the icon @k0nserv :) 

The blue flame variant is also great - I just used @jwilm's choice. Further icon discussion should belong in #285 to keep it one place.

**Comment by jwilm** [comment]
Hey @net,

Thanks for bringing that up. After trying out the icon in my dock for a few days, I've got a little bit of additional feedback. Specifically, I'm worried that it might not read well at small sizes, and it might not read as well against a dark background.

Reading well at small sizes can be improved by rendering the SVG at lower dimensions instead of downsizing pngs as we've done so far. Additionally, it might be nice to move the flame down just a bit.

As for the dark backgrounds, I'm thinking that maybe a lighter border would be good. Here's a mockup for example:

sidebar

Looking forward to hearing your thoughts :)

**Comment by net** [comment]
@jwilm I agree the icon could be improved for darker backgrounds, though perhaps it is not necessary to be quite as light as the one in your mockup. Another option could be to offer dark background and light background variants.

I'll take a look at it, and submit an SVG tomorrow if I remember. Smaller rendered PNG can also be extracted from the .icns files I posted in the other issue.

**Comment by net** [comment]
We could display just the Λ with no terminal border for smaller sizes.

**Comment by nirfse** [comment]
@net Could you provide a screenshot of a simple small Λ icon?
@jwilm I suppose the better contrast could be achieved with a slight background gradient, or with very thin outline (same as Terminal.app icon):
image

But it's still better to keep plain black icon than a bright glowing around it.

**Comment by jwilm** [comment]
One other option is potentially brightening the current gradient on @net's icon. Nothing extreme, just enough to make it stand out on a dark background.

Aside from design details, is there a better way to host this icon than within the Alacritty git repo? I am trying to avoid bloating the repo size, and I slightly regret already merging icons for macOS in the past.

**Comment by jwilm** [comment]
Closing this for now until we get the final icon. I filed an issue to track remaining work.

**Pull request closed without merging**
