### PR TITLE
readme: Remove stray line

### PR DESCRIPTION
**Pull request by polyzen**
No longer needed thanks to #382.

### CODE REVIEW

**Comment by jwilm** [comment]
Doesn't the AUR package need to be updated? #383

**Comment by polyzen** [comment]
Actually, looks like that's [already been done](https://aur.archlinux.org/cgit/aur.git/commit/?h=alacritty-git&id=db23d93122a2765bccd6beb95fb142ca1ceb2ffa), and people have had to manually add the rustup line to the script.

**Comment by jwilm** [comment]
Oh, interesting. That must be why the build was broken from AUR

**Comment by jwilm** [comment]
thanks!

**Comment by polyzen** [comment]
Thank you. :)

**Pull request merged**
