### PR TITLE
Change font size only when new metrics are valid

### LINKED ISSUE #1693: Decreasing font size too much causes division by zero
Which operating system does the issue occur on?
Windows. I have also tested on Linux/X11 and could not reproduce there.

Version of alacritty:
4380d0864b1098909bdcfec132b866c34924517e

How to reproduce:
1. Open alacritty
2. Press `Ctrl`+`-` to scale the font down until it disappears
3. Move mouse over the window
4. alacritty crashes with the following stack trace:

```
$ RUST_BACKTRACE=1 ./target/debug/alacritty.exe
thread 'main' panicked at 'attempt to divide by zero', src\term\mod.rs:810:26
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:52
  11: alacritty::term::SizeInfo::pixels_to_coords
             at .\src\term\mod.rs:810
  12: alacritty::input::Processor<alacritty::event::ActionContext<alacritty::event_loop::Notifier>>::mouse_moved<alacritty::event::ActionContext<alacritty::event_loop::Notifier>>
             at .\src\input.rs:327
  13: alacritty::event::Processor<alacritty::event_loop::Notifier>::handle_event<alacritty::event_loop::Notifier>
             at .\src\event.rs:358
  14: alacritty::event::{{impl}}::process_events::{{closure}}<alacritty::event_loop::Notifier>
             at .\src\event.rs:461
  15: alacritty::event::Processor<alacritty::event_loop::Notifier>::process_events<alacritty::event_loop::Notifier>
             at .\src\event.rs:472
  16: alacritty::run
             at .\src\main.rs:231
  17: alacritty::main
             at .\src\main.rs:80
  18: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  19: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  20: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  21: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  22: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  23: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  24: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  25: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  26: main
  27: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  29: BaseThreadInitThunk
  30: RtlUserThreadStart
```

When I add a following check, it hits the newly added panic on hitting the last `Ctrl`+`-` to scale the font down:
```diff
diff --git a/src/display.rs b/src/display.rs
index d5a2ea0..1896e88 100644
--- a/src/display.rs
+++ b/src/display.rs
@@ -261,6 +261,11 @@ impl Display {
         let metrics = cache.font_metrics();
         self.size_info.cell_width = ((metrics.average_advance + f64::from(config.font().offset().x)) as f32).floor();
         self.size_info.cell_height = ((metrics.line_height + f64::from(config.font().offset().y)) as f32).floor();
+
+        // Prevent invalid cell sizes
+        if self.size_info.cell_width < 1. || self.size_info.cell_height < 1. {
+            panic!("font offset is too small");
+        }
     }
 
     #[inline]
```

### PR DESCRIPTION
**Pull request by martin-sucha**
This fixes #1693

### CODE REVIEW

**Comment by martin-sucha** [comment]
I've just started learning Rust, so if you spot something that is not idiomatic Rust, please let me know.

**Comment by chrisduerr** [comment]
Thanks for the PR! I've taken an initial look at this fix and the approach looks good to me.

I'd like to get #1403 merged before this, so this PR will probably need to resolve some conflicts once that's done.

**Comment by chrisduerr** [comment]
Now that #1403 is merged, this can be rebased on top of the latest master.

One thing I've been wondering about is how this would behave if the font cell size would just be fixed at 1 rather than throwing an error if it goes below it. If that works well, maybe we can save ourselves from having to handle the error case.

**Comment by martin-sucha** [comment]
That could work too. Although maybe we'll want to disable decreasing font size if either cell width or cell height is 1, so that increasing the font again will be visible immediately. I won't have time to look at this at least in the next two weeks though, so feel free to try it out in the mean time if you want.

**Comment by chrisduerr** [comment]
Yeah, it definitely shouldn't take a couple of presses to get from 1 to > 1 then. Completely agree with you there.

**Comment by chrisduerr** [comment]
I've taken the freedom to update this myself since there hasn't been any progress on this PR in a while.

This should hopefully resolve the problem, it seems to be working great on Linux when using a negative font offset.

**Comment by chrisduerr** [comment]
@zacps @martin-sucha I'd welcome some help with testing this on Windows, so we could include it in our next release. Hopefully this should just work now.

**Comment by chrisduerr** [comment]
Since this resolves the problem on Linux, it should be fine to merge this and let people with various fonts test this.

Though I'd still be curious about explicit tests on Windows.

**Comment by martin-sucha** [comment]
@chrisduerr I've built latest master on Windows and the problem is resolved on Windows too. Thanks for fixing it!

**Pull request merged**
