### PR TITLE
Print config error warning on startup

### LINKED ISSUE #1143: Config failure should be printed in the new alacritty instance
When starting alacritty with a faulty config, the errors are printed to `stderr`. However this only helps when starting alacritty from another alacritty instance.

To make debugging more obvious on users warnings and error should also be printed to the newly launched alacritty process. This will clearly indicate to the user if something is wrong without having to launch from another terminal.

Another benefit of this could be a faster adoption of new config layouts. If deprecation warnings are printed whenever starting a new terminal, it will strongly encourage the user to actually make changes so we can quickly remove things.

### PR DESCRIPTION
**Pull request by chrisduerr**
This change adds an error message at the bottom of the screen which will
be displayed when the config file contains any errors.

Currently deprecation warnings are unchanged but it would be possible to
add these too (maybe in yellow?) if it is desired.

The method for rendering text has been changed to always render at the
bottom of the terminal, this seems like a more reliable way of doing
this and it shouldn't cause any issues because under normal use, nothing
should be displayed.

I'd say this is still a bit rough around the edges so feedback is
welcome, maybe some things could be streamlined?
Currently if the terminal is not wide enough, nothing will be displayed,
maybe we should display the message but cut off? Not sure how important
this is because it would probably be fine to not display anything in
small terminals.

All errors are written to `/tmp/alacritty.log`, nothing is written to
stderr anymore, we could do both but I think it should not be necessary
to write anything to stderr anymore.

This fixes #1143.

### CODE REVIEW

**Comment by NickeZ** [comment]
What is the reason for not printing to stderr? That would be the first place i would look if something was wrong with Alacritty

**Comment by chrisduerr** [comment]
It would be a simple fix to print both to stderr and a log file, however when starting alacritty you usually don't have access to stderr (without having to attach to the process).

So unless you start alacritty from another instance of alacritty, you will not be able to see the errors. Having a log file will allow you to always see the errors even when alacritty doesn't launch anymore and you don't have another terminal for checking the stderr.

**Comment by NickeZ** [comment]
Yeah but I wouldn't go look for a log file in /tmp. First I would run alacrity with another terminal and look at stderr. Then i would look for a .alacritty-log (like how the xserver does) in my home folder.

**Comment by chrisduerr** [comment]
Have you tested this PR? It will show an error message to the user which states that errors have been written to `/tmp/alacritty.log`, so I think it should be fine.

I really don't like the idea of writing error logs in the home folder because it might create unnecessary files that could clutter the home directory of a user even long after alacritty is removed.

**Comment by NickeZ** [comment]
No I didn't test this PR. I think it is great that you will print the error in the Alacritty window. But, what if Alacritty exits for some reason. Will you still see the message that there is a logfile somewhere? Maybe you can print where the logfile is to stderr. I do still think that printing to stderr should be the default, what if /tmp isn't writeable, is there a fallback to stderr?

**Comment by chrisduerr** [comment]
I'm now writing the errors to both the log file and `stderr`. However alacritty should never instantly crash when config errors are present, so when such an error appears it will never be logged but rather cause a panic that is untracked.

**Comment by NickeZ** [comment]
Ok! I misunderstood and thought this PR was all errors. If it is only config errors that are logged to file I don't have that strong opinion. But I still think it is good to be consistent and log everything to the same place. Which I guess is stderr in this case.

**Comment by NickeZ** [comment]
It would also be nice to use the printing facility that is implemented in this PR to print for example the new font size when pressing `ctrl` `+`/`-`.

**Comment by chrisduerr** [comment]
I'm actually not a huge fan of the current shape of this PR, I think it's a bit awkward and doesn't really allow any other event to hook into the file logging and error/warning printing.

I think logging things like the font size change would be a great idea, at least if the required logging verbosity is specified.

**Comment by chrisduerr** [comment]
I've decided to reimplement the complete PR rather than trying to resolve some remaining issues I've had with it.

I think the way this works should be a lot better now. There's no more globals being accessed across the complete codebase and generally things have been simplified a lot.

All warn! and error! logs are now printed to a log file and stdout by default. If any error or warning is created, it is displayed in the UI with a notice about the location of the log file. This allowed removing all calls to `print!`, `eprint!`, `println!` and `eprintln!`.

There were two slight complications with getting rid of printing to the command line directly. The `--print-events` flag has been changed so it will automatically set the log level to info (like `-v`). Then all messages are just printed using `info!`. It's still checked that `--print-events` is present though, so the events are not always printed when the info level is set.

The other problem was with warnings about escape sequences which are currently still emitted on a regular basis. This would cause a ton of warnings for most users. Since there has been some confusion about these messages anyways, the log level has been reduced to `debug`. This might make debugging harder in some cases, but I think it's a good solution now that Alacritty has support for most basic escapes.

**Comment by NickeZ** [comment]
It seems to me that `env::temp_dir()` is the global temporary folder and not the users temporary folder. Does this mean that the second user opening alacritty can't log to file? I would prefer that we use a user-local log directory such as `$XDG_CACHE_HOME` or `$XDG_DATA_HOME`.

I'm sure this will not be a very common problem, but I've had problems with running software using sudo and then not being able to start the software as my own user because the logfile now was owned by uid 0.

**Comment by NickeZ** [comment]
Another idea is to add the process id to the logfilename and keep storing it in the global tmp.

**Comment by chrisduerr** [comment]
@NickeZ Those are some good points. Right now the global log file is used by all Alacritty instances. That means that all write to it at the same time, it's not locked to one specific process.

I've actually put it onto my todo list to test what happens when the user isn't allowed to write to the file, it should just prevent file logging from working, but I haven't tested that yet.

I've thought about multiple different ways to create logfiles with some kind of hash/time/id in the name, but I decided to go with a global log file for now. I think using the `PID` of Alacritty is probably the best of the choices I've evaluated, so I think using that would be fine. Note though that with 13 open Alacritty windows, this will spawn 13 files if you change your config and there's an error. This could also override previous files without restart because a PID can be reassigned, but I'd say that's irrelevant.

I think putting it in the user home directory is a bigger problem. There is no standard temporary user directory which gets automatically cleared, so Alacritty runs the risk of just dumping a ton of log files which will never be read or deleted. I think `/tmp` is a great place for discoverability and adding a PID should help with access problems, however it would still be possible to run into an issue if the PID is reused.

An alternative for a global temp directory would be a user-based temporary directory provided by `systemd`. It's located at `/run/user/$UID` and is automatically cleared at startup. However this will cause problems with Windows, macOS, BSD and every Linux distro not running systemd. Unless you have a good solution for that, I think using `env::temp_dir` is our best bet for making things work everywhere.

**Comment by NickeZ** [comment]
Ok, sounds like you thought about it. Another thing that is not immediately obvious to me after reading the code. Will it always log to file or only when `-v` is given?

**Comment by chrisduerr** [comment]
@NickeZ Warnings and Errors are always logged to the file. Other stuff is only logged when `-v(vv)` is present.

**Comment by chrisduerr** [comment]
The proposal from @NickeZ has now been incorporated into the latest commit.

I still need to do another full code review to make sure the code quality is okay, but I think the functionality should be pretty much there now. If there's any remaining problems or ideas for improvements, please let me know.

**Comment by chrisduerr** [comment]
Instead of always keeping all logfiles, I've made the decision to delete logs by default once Alacritty is closed. If the CLI parameter `--persistent-logging` or the configuration option `persistent_logging` are set, the log file will not be deleted after closing Alacritty.

As always, feedback would be appreciated. I don't think there's any further issues I have with this PR, but I'm unsure if the additional configuration option plus CLI flag are absolutely necessary.

**Pull request merged**
