### PR TITLE
Fix selection in scrollback

### LINKED ISSUE #1159: Selection in scrollback off by one
When selecting on a line and then moving the mouse to the line below, selection will move one cell to the left in the first line of the selection.

If this is done at the beginning of the line, the selection is completely messed up.

Here's a gif to make the issue obvious:
https://u.teknik.io/yAmKj.webm

### LINKED ISSUE #1182: Selection moving off screen glitch
When selection moves off the screen, it jumps around a bit right now. I think a solution which first resolves a selection to _buffer_ coordinates and then clips and transforms to screen space would not exhibit this problem.

### PR DESCRIPTION
**Pull request by chrisduerr**
There were a few issues with selection in scrollback that were mainly
off-by-one errors. This aims at fixing these issues.

This also fixes a bug that currently exists in master where the last
cell is not selected when the mouse leaves the window to the right.

This fixes #1159 and fixes #1182.

### CODE REVIEW

**Comment by jwilm** [comment]
This has conflicts on current scrollback branch

**Comment by chrisduerr** [comment]
I've rebased on master, fixed a tiny bug with selecting the first cell in a multi-line selection and am now propagating mouse events outside of the window to update selection.

The screen does not scroll automatically yet, but this is probably better done in a different PR.

**Comment by jwilm** [comment]
Is this ready to go? You mentioned elsewhere about improving the selection clipping behavior in this PR.

**Comment by chrisduerr** [comment]
After fixing the edge-cases for the remaining issues, the `span_simple` method feels like a bit of a mess to me. If all other scrollback issues are resolved, this would probably be fine, but I'd like to re-think this approach while there still are some other open issues and we have some time.

There definitely are quite a few edge-cases for this, but it might be interesting to try and rewrite this completely with these edge-cases in mind to see if it can be cleaned up. Right now it seems like it's more edge-cases than anything else really.

**Comment by jwilm** [comment]
The `span_simple` is ironically named huh.. :upside_down_face: 

The crux of the problem is that we need to be able to handle single cell selection without triggering a selection on every simple click. If you have ideas on how to approach that without the idea of "sides" of a cell, then that would simplify things dramatically.

**Comment by chrisduerr** [comment]
I don't think the idea of `sides` is bad. Even if we wouldn't want to pass `sides`, we'd probably still do something like remove one from column when at the right under certain circumstances, which would be sides again, only handled in the method above it.

I think with my implementation I've got a bit confused by the `SpanType`. With my approach of fixing these issues it always kinda got into the way because I just wanted to go from cell XY to cellXY including everything from start to end. Properly using this might help with some edge cases.

I think by just rewriting the method from scratch without having to understand what's already there, I might be able to get a better result. Worst-case I'd probably re-implement the same thing again. It's a short method so I think it's worth exploring.

For now I'd rather keep this open and I'll get back to it this weekend or earlier when I have the time. If I didn't find any better solution until the other things are fixed, it's probably fine to merge it as-is.

**Pull request merged**
