### PR TITLE
Implement block selection

### LINKED ISSUE #978: Block selection
Unphased has mentioned in #974 that block selection would be a nice feature for alacritty. And I'd love to take a look at implementing this.

The main question would probably be about which modifier should be used for it. I'd go for ctrl, which is used by VTE, but it seems like other terminals use alt.

### PR DESCRIPTION
**Pull request by chrisduerr**
Basic block selection has been implemented. This fixes #978.

Currently this still uses a fixed key, which is `ctrl`. It might be desirable to use a configurable key option for this, but I wasn't sure if I should put that in the key shortcuts, or if a separate option outside of the key options should be used.

One issue with setting up a `key_binding` is that especially when keys like control or shift are used, they might be counted as modifiers. So when holding shifit and pressing control, it would be a different key combination. So this key would need to be setup to catch the key itself and all modifiers.

It would also be the first key that requires a separate release event as far as I know. So that might be some code complexity that would not be desired.

### CODE REVIEW

**Comment by chrisduerr** [comment]
The block selection key is now configurable. This uses the
`key_bindings` section in the configuration with the new
`BlockSelection` action. I'm not a huge fan of the way this works
myself, but it should give an example of what might be possible for a
configurable shortcut for this.

**Comment by maximbaz** [comment]
You should add the 2 lines of config above to `alacritty.yml` and `alacritty_macos.yml`, both of them should be there by default, especially after #974 is merged 🙂

In general, block selection works good.

**Comment by chrisduerr** [comment]
I didn't add them to the config yet because I'm not 100% happy with the way this works. I don't think doing it like this is a good idea, it's probably better to have a separate setting for it outside of the `key_bindings` section. I don't think it should be possible to configure any key and I think this flexibility hurts the user experience rather than improving it. Keeping it simpler and allowing just two key (alt and ctrl) seems like the better choice to me at this point.

**Comment by chrisduerr** [comment]
I have now played around with making this a separate setting in the config and I think we should be able to do it like this. It's a simple `alt_key_block_selection: true` to enable block selection with the alt key. I don't think any key other than Control and Alt makes sense, so I really like this way of configuration. I think this is probably the right way to do this and I'm gonna keep it like this for now.

**Comment by chrisduerr** [comment]
I'd recommend not merging this yet. I'm currently working on clearing the selection (tracked in #836) and it might be easier to combine these two changes into one PR, because I might make use of the `SelectionRect` to replace the current way selections are stored.

**Comment by unphased** [comment]
@chrisduerr I can't merge this in together with your other 2 branches (faux scroll (master) and shift-select) so I can't test. will just wait. Thanks.

**Comment by chrisduerr** [comment]
Closing this for now because it really is nicer to do block selection and my selection reworks in one PR. I'm probably gonna open the new PR in a few hours.

**Comment by unphased** [comment]
@chrisduerr were you planning on putting block selection into selection changes? Or, now that selection is merged, that is.

**Comment by chrisduerr** [comment]
Currently not working on selection. It might land with scrollback, they are kinda related.

**Comment by unphased** [comment]
awesome! Thanks for your contributions 💯

**Pull request closed without merging**
