### PR TITLE
Make visual bell flash color customizable (#2)

### PR DESCRIPTION
**Pull request by chrisduerr**
This addresses the main feedback in jwilm/alacritty/pull/430. I've
decided to go from scratch instead of basing my work on top of what
markandrus has already implemented to keep it as simple as possible.

If there's any stuff that I should take from the other PR, please let me
know. I can also try to send a PR to markandrus.

### CODE REVIEW

**Comment by jwilm** [comment]
This looks good. I was playing around with this and noticed the bell messes with background colors; it just doesn't feel right. As it turns out, simply using the clear color for visual bell gives pretty reasonable results. Here's a diff you can try:

<details><summary>bell without shaders</summary>

```diff
diff --git a/res/text.f.glsl b/res/text.f.glsl
index c551179..532cf92 100644
--- a/res/text.f.glsl
+++ b/res/text.f.glsl
@@ -15,8 +15,6 @@
 in vec2 TexCoords;
 in vec3 fg;
 in vec4 bg;
-in vec3 vbc;
-flat in float vb;
 flat in int background;
 
 layout(location = 0, index = 0) out vec4 color;
@@ -32,11 +30,7 @@ void main()
             discard;
 
         alphaMask = vec4(1.0);
-        if (vb == 0) {
-            color = vec4(bg.rgb, 1.0);
-        } else {
-            color = vec4(vbc, vb);
-        }
+        color = vec4(bg.rgb, 1.0);
     } else {
         vec3 textColor = texture(mask, TexCoords).rgb;
         alphaMask = vec4(textColor, textColor.r);
diff --git a/res/text.v.glsl b/res/text.v.glsl
index a13d99a..25f2821 100644
--- a/res/text.v.glsl
+++ b/res/text.v.glsl
@@ -32,7 +32,6 @@ layout (location = 5) in vec4 backgroundColor;
 out vec2 TexCoords;
 out vec3 fg;
 out vec4 bg;
-out vec3 vbc;
 
 // Terminal properties
 uniform vec2 termDim;
@@ -44,7 +43,6 @@ uniform int backgroundPass;
 
 // Orthographic projection
 uniform mat4 projection;
-flat out float vb;
 flat out int background;
 
 void main()
@@ -76,8 +74,6 @@ void main()
         TexCoords = uvOffset + vec2(position.x, 1 - position.y) * uvSize;
     }
 
-    vb = visualBell;
-    vbc = visualBellColor;
     background = backgroundPass;
     bg = vec4(backgroundColor.rgb / 255.0, backgroundColor.a);
     fg = textColor / vec3(255.0, 255.0, 255.0);
diff --git a/src/renderer/mod.rs b/src/renderer/mod.rs
index 65db324..436b4b8 100644
--- a/src/renderer/mod.rs
+++ b/src/renderer/mod.rs
@@ -115,12 +115,6 @@ pub struct ShaderProgram {
     /// Cell dimensions (pixels)
     u_cell_dim: GLint,
 
-    /// Visual bell
-    u_visual_bell: GLint,
-
-    /// Visual bell color
-    u_visual_bell_color: GLint,
-
     /// Background pass flag
     ///
     /// Rendering is split into two passes; 1 for backgrounds, and one for text
@@ -647,12 +641,9 @@ impl QuadRenderer {
             }
         }
 
-        let visual_bell_color = config.visual_bell().color();
-
         unsafe {
             self.program.activate();
             self.program.set_term_uniforms(props);
-            self.program.set_visual_bell(visual_bell_intensity as _, visual_bell_color);
 
             gl::BindVertexArray(self.vao);
             gl::BindBuffer(gl::ELEMENT_ARRAY_BUFFER, self.ebo);
@@ -995,13 +986,11 @@ impl ShaderProgram {
         }
 
         // get uniform locations
-        let (projection, term_dim, cell_dim, visual_bell, visual_bell_color, background) = unsafe {
+        let (projection, term_dim, cell_dim, background) = unsafe {
             (
                 gl::GetUniformLocation(program, cptr!(b"projection\0")),
                 gl::GetUniformLocation(program, cptr!(b"termDim\0")),
                 gl::GetUniformLocation(program, cptr!(b"cellDim\0")),
-                gl::GetUniformLocation(program, cptr!(b"visualBell\0")),
-                gl::GetUniformLocation(program, cptr!(b"visualBellColor\0")),
                 gl::GetUniformLocation(program, cptr!(b"backgroundPass\0")),
             )
         };
@@ -1013,8 +1002,6 @@ impl ShaderProgram {
             u_projection: projection,
             u_term_dim: term_dim,
             u_cell_dim: cell_dim,
-            u_visual_bell: visual_bell,
-            u_visual_bell_color: visual_bell_color,
             u_background: background,
             padding_x: config.padding().x.floor(),
             padding_y: config.padding().y.floor(),
@@ -1060,17 +1047,6 @@ impl ShaderProgram {
         }
     }
 
-    fn set_visual_bell(&self, visual_bell: f32, vb_color: Rgb) {
-        unsafe {
-            gl::Uniform1f(self.u_visual_bell, visual_bell);
-            gl::Uniform3f(self.u_visual_bell_color,
-                          vb_color.r as f32 / 255.,
-                          vb_color.g as f32 / 255.,
-                          vb_color.b as f32 / 255.
-            );
-        }
-    }
-
     fn set_background_pass(&self, background_pass: bool) {
         let value = if background_pass {
             1
```

</details>

**Comment by markandrus** [comment]
Nice. I’d like to see something like this land (just switched back to Alacritty on a new laptop of mine and was wanting this).

**Comment by jwilm** [comment]
I just remembered why we have the shader part of the bell, and I think it's because sometimes vim+tmux users want a different background color for the editor. Perhaps the right solution is to draw a big quad for the visual bell on top of everything else.

**Comment by chrisduerr** [comment]
By "big quad" you mean just drawing over everything and then increasing/decreasing alpha for the flash? Wouldn't that look similar to this PR?

**Comment by unphased** [comment]
I think my two cents here would be to try to have a system that is simple and powerful. I suppose the most powerful thing that one might realistically want to have for something like a visual bell might be to allow for the specification of a post-processing fragment shader that receives a float uniform for timing, that way the shader could implement the timing function too!

The motivation here would be the ability to make "fancy" and "cool" visual bells. Imagine something like a "glitch" effect, or a gaussian blur perhaps. Or a movement based transformation, as subtle or conspicuous as you want, really. 

But I must also concede that this would not be user friendly because shaders are not trivial to understand, and it absolutely does feel like giving users some measure of control over the timing function (and duration, of course) without simultaneously worrying about modulating the appearance would be good. Plus, opening up shaders to config is often a potential DoS vector. 

Realistically to stay on topic and not hijack this with considerations for the timing-func/animation (but if I may for just one aside: I can't say that I love the animation choice between timing functions -- I'd love that more if it gave me e.g. the ability to paste in a bezier curve like from http://cubic-bezier.com/#.17,.67,.83,.67): I think Alacritty should just start off with a minimalistic visual bell that has a few simple knobs that can be tweaked. 

And just modulating the background color does seem fine, except for how it's entirely possible to configure an overriding bgcolor in tmux and that will actually cause the term's bgcolor to get overridden for probably all characters, which will make a bgcolor-only visual bell fail to do anything. 

Personally I like to do this thing where I set the terminal's bg color to something and give it slight transparency (around 0.93 alpha is nice) and have tmux configured to provide an overriding bg color for only the active pane:
```tmux
set -g window-style 'bg=default'
set -g window-active-style 'bg=#000000'
```
My long comment more or less amounts to "yes we should do a full screen overlay" because it opens the door for arbitrary post-processing, which can be neat. And a full screen quad is perfectly reasonable to go about that, I don't know much about the rendering pipeline at this point yet.

**Comment by chrisduerr** [comment]
I personally don't really see a reason to have some special visual effects for the bell. To me this mostly seems like a "gimmick" and nothing that would actually be useful. I don't think this complexity of a more advanced configuration of the visual bell should be put on the user and the code should also stay lean and straight to the point for such a basic feature.

**Comment by unphased** [comment]
yes, I'd say that a quad that just has an animated alpha value with configurable color will support the concern about the background color being "covered up" by a tmux or other such terminal pseudoterminal program.

**Comment by chrisduerr** [comment]
@markandrus Would you be interested in looking into rendering just one big quad over everything? Unfortunately I'm not very experienced with OpenGL so it will probably take me a while until I can find the time to work on this more.

**Comment by chrisduerr** [comment]
So I've made some pretty major changes. It's now rendering only one big quad as requested.

The commit message should explain most of these changes:

```
A method `render_rect` has been added that allows drawing a rectangle
over anything in the terminal. This is used by the visual bell to draw a
big rectangle over everything.

To achieve this a new shader has been added. Shaders are now kept around
until the program is dropped. Then whenever a rectangle draw call is
issued, the shader is swapped from the default shader to the rectangle
drawing shader.

After the shader has been swapped and the rectangle has been drawn,
uniforms (like projection) and blending function are reset to make sure
the rendering can be continued on the default shader.

All current instances of visual_bell in the rendering have been removed,
it is now all done exclusively through the rectangle rendering function.

Currently the shaders are swapped every time `render_rect` is called, so
when rendering multiple rectangles (potentially for underline /
strikethrough) there would be a loads of shader swaps that could be
potentially very expensive.

So before using `render_rect` for a different application, the shader
swap should be removed from the `render_rect` method.
As long as the visual bell's alpha value is 0, this has no effect on
performance because no rectangle is rendered.
```

**Comment by chrisduerr** [comment]
I've just found out that this still has an issue with the projection not properly updating and text looking weird with big paddings:

bug

And a different issue which is probably related (no padding on right):

bug

**Comment by chrisduerr** [comment]
This bug should be fixed now. Everything should be good for merge again.

**Comment by PlasmaPower** [comment]
Any update on this?

**Comment by chrisduerr** [comment]
New features are probably gonna have to wait until scrollback is merged.

**Comment by evaryont** [comment]
Given underline support (#1078) depends on this PR being merged, is there anything we can do to help @chrisduerr get this ready again?

**Comment by chrisduerr** [comment]
@evaryont Before getting to this PR, I'll have to get to the other PRs which are still open. I'm currently working on finishing one of those old PRs (#1329), but it just takes time.

Especially since lots of these old PRs need some more work (at least a rebase on top of master), this can be a bit time intensive.

There always are things you can do to help though. If there's any issue or PR you feel comfortable helping out with, just help out. Feel free to ask any questions on github or IRC. The more people help out, the faster things will go. Unfortunately I also only have a limited amount of free time.

**Comment by chrisduerr** [comment]
Merged master into this again and while there were some issues with the new way DPI is handled, I believe the functionality should be on point again.

Before this can be merged, there are somethings left to be done though:
 - [ ] Make sure DPI scaling works properly (more testing needed on high DPI screens)
 - [ ] Create abstraction for calculating dynamic padding

The abstractions for the dynamic padding are required because there are now three different locations in the code where the dynamic padding is calculated and one of them has an off-by-one error present (see the `TODO` annotation). To resolve these problems and make sure more aren't introduced in the future, there should only be a single method for getting the padding with dynamic padding applied.

**Comment by chrisduerr** [comment]
Looks like everything's good to go now. Performance is unchanged, which makes sense since it only touches rendering code and we have lots of headroom there.

Tested on different DPIs too and everything's looking good. Should be able to merge this if CI doesn't complain and then go on to #1078.

**Comment by unphased** [comment]
Sorry for the noise, but I still can't find a way to configure visual_bell in a way that doesn't induce a blinding white flash. the ease will go from full-white toward the specified color, and then fade, but that isn't really useful.

**Pull request merged**
