### PR TITLE
Extract dpr based vars into method. Rebuild on resize

### PR DESCRIPTION
**Pull request by trashhalo**
Fix for #71 atleast resizing seems to still work.

~~**DO NOT MERGE**: have to wait until I get to work to try it on retina monitor. Will update with result.~~

Note: I have no idea what I am doing in rust. Im a node/ruby guy. I'll change anything you want me to change!

### CODE REVIEW

**Comment by robertgzr** [comment]
@trashhalo I tested your changes going back and forth between 255 macbook and 331 dpi external monitor and it works great 👍

**Comment by jwilm** [comment]
Hey @trashhalo,

Thanks for the PR! I was pretty excited someone was looking into this issue; why did you decide to close it?

**Comment by trashhalo** [comment]
I found a bug :( was going to try and fix it tonight. After it changes dpr something is holding onto the old font size. You can see the fonts overlapping in the image below.

screen shot 2017-04-11 at 12 38 02 pm

**Comment by trashhalo** [comment]
@jwilm I fixed the bug!!! I had to update the terminal cell width height when this happens. One quick note Im not seeing the resize event called on screen change so I need to look into that more but this atleast provides a work around. After moving window between screens resize it to cause the dpr reboot.

It looks like we need to bump glutin/winit to get the resize event to fire since that was only added 25 days ago. https://github.com/tomaka/winit/commit/cccc48b84d403b6957b31c5172db1367ed42762d

**Comment by trashhalo** [comment]
@jwilm this guys been sitting out there for a couple weeks now. anything you want me to change?

**Comment by jwilm** [comment]
Hey @trashhalo,

Sorry for the delay in addressing it. Slowly getting back into the swing of things with Alacritty :)

Anyway, this looks good overall, but there's one sort of big issue. When you are replacing the GlyphCache, we don't clean up the OpenGL resources used by the previous glyph cache. Basically, we either need to release the previous texture and get a new one, or even better, just take the texture name from the previous cache and use it in the new cache.

**Comment by trashhalo** [comment]
@jwilm okay pr updated to drain atlas deleting textures attached on drop. I thought about doing something more clever like a texture reuse. But decided it would really complicate the algorithm for little visual benefit for the user. The assumption here is calls to resize are a infrequent event.

**Comment by vrinek** [comment]
**Usage report** I've been using this for a couple of weeks now (retina laptop plus non-retina display) compiled from source of https://github.com/jwilm/alacritty/pull/510/commits/4055beb8c04bb386472ee8a5dddb37fa680fb1dc.

- When I have a small window and move it myself between screens, it still behaves buggy (with the font changing between screens)
- When I have the window occupying a large part (larger than the laptop screen) of the external monitor and then I disconnect the monitor, macOS moves the window to the smaller laptop screen **and resizes the window to fit the smaller screen**. In this case, the bug does not manifest.

Because of the above I think that the assumption that a change of screen fires a "resize event" may not hold.

**Comment by trashhalo** [comment]
@vrinek 
> Because of the above I think that the assumption that a change of screen fires a "resize event" may not hold.

You are totally right it doesn't because this project is using a old version of winit. Firing a resize on screen changes was only introduced recently.

**Comment by davesque** [comment]
Any updates on this?  Would love to see this issue resolved.  I often move an open Alacritty window between two monitors with different DPI so I run into this issue every day.  Thanks for the work in trying to address this!

**Comment by jwilm** [comment]
The core functionality added here is on master due to dynamic font resize support. Additionally, _winit_ is adding an event for DPI change events which will be much cheaper than regenerating the font cache on every resize. I'll file an issue for using that new event type once it's available.

**Pull request closed without merging**
