### PR TITLE
Ignore errors when logger can't write to output

### LINKED ISSUE #1457: Alacritty crashes when printing errors without stderr available
Which operating system does the issue occur on?
Fedora 28
If on linux, are you using X11 or Wayland?
X11, bspwm with sxhkd

I initially encountered this bug when launching alacritty with a `sxhkd` binding. Usually, alacritty would behave as expected, but following a strange systemd-related event where messages like this would be generated,
```Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 226:0
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:67
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:71
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:73
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:72
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:70
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:68
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:74
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:65
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:76
Jul 21 14:36:27 f /usr/libexec/gdm-x-session[2021]: (II) systemd-logind: got pause for 13:66
```

I would get (after restarting sxhkd to regain keyboard input) this bug in alacritty. Gnome-terminal (launched from alacritty) would open nvim fine. Also, running alacritty from alacritty would allow the spawned alacritty to open nvim, and it would print "Unhandled CSI" errors into the terminal used to spawn it. (https://github.com/jwilm/alacritty/issues/857#issuecomment-405226776). 

Finally, I tried changing my `sxhkd` binding from `alacritty` to `alacritty > /dev/null`. This fixed the problem, and leads me to suspect that alacritty will crash if it needs to output these "unhandled CSI" errors without a stdout to print to. 

It is, however, also possible that this is an sxhkd bug in spawning alacritty. And there is certainly some problem with systemd-logind creating these pause messages during normal usage (not at lid close time). Sorry for the big mess, hopefully this is not too complicated to fix.

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes #1457.

### CODE REVIEW

**Comment by chrisduerr** [comment]
This needs some more work, waiting for a coredump in #1457 to further troubleshoot this.

**Comment by chrisduerr** [comment]
I've decided to go against rushing #1188 and rather take the safer approach here which will fix the issue without requiring many changes.

Instead of reworking the logging/error reporting, this simple overwrites the `eprintln` and `println` macros to ignore errors.

@expectocode can you confirm that this solves the issue for you?

**Comment by expectocode** [comment]
Will test this later, but you should note that the print! macro has the same panic

**Comment by expectocode** [comment]
Speaking of tests, this might warrant a regression test (though i'm not at all familiar with how this project does things)

**Comment by chrisduerr** [comment]
Thanks for the notice that the `print!` macro also fails, but luckily that's never used in Alacritty at this point.

Testing this is a great idea, I'm not entirely sure how much change it will require to allow specifying a custom stdout/stderr (so I can make it fail), but I'll definitely look into it!

**Comment by expectocode** [comment]
Nice work! 
Trying it out, seems to have fixed my issue (with the stderr print, at least. stdout one is hard to recreate). But there might be more i/o panics in the code waiting to be triggered (I found some uses of print! under `font`: https://github.com/jwilm/alacritty/search?q=print!, not sure if these would happen at run time though).

**Comment by chrisduerr** [comment]
@expectocode `font` should never print anything directly to the user, since it's just a library used in the background. All instances of `(e)print` and `(e)println` inside of `font` are part of test code.

Thanks for being so thorough with checking this, I have forgotten about the subcrates, but it looks to me like this shouldn't be any issue.

**Pull request merged**
