### PR TITLE
Fix #447 - yml: mention `showkey -a` to get x sequence from key

### LINKED ISSUE #447: Unable to use Ctrl+{PageUp,PageDown} - unbound in default yml / missing documentation?
Hi,

I'm able to use alacritty with my existing tmux configuration, but some key combinations don't work.

* **Working**: `Shift+{Left, Right, Up, Down}` (which I use to switch panes), `Ctrl+B` (which I use to (un-)maximize panes, and a slew of others that work as expected.
* **Broken**: `Ctrl+{PageUp,PageDown}` don't do anything, even though I bound them in tmux to `next-window` (letting me "switch tab" like in a web browser), and they work as expected in gnome-terminal. Same for `Shift+{PageUp,PageDown}`, which I bound to tmux `previous-page` and `next-page`.

Then I'm unsure what to do at this point:

* Is this a bug?
* If not, is it missing configuration? I see in my `alacritty.yml` that the *working* key combinations are listed in `key_bindings` (e.g. `{ key: Left, mods: Shift, chars: "\x1b[1;2D"}`) and indeed my *non-working* Ctrl+PgUp/Dn are not bound.
    * So I'd like to create two such bindings for Ctrl+PgUp/Down, but I have no idea what `chars` I should bind (Shift+Left was `\x1b[1;2D`, what is Ctrl+PgUp? My googling attempts were unsuccessful as I don't know how to *name* this thing I'm looking for: what is this string? A "tty character"? a "tty sequence"?
    * To prevent questions like mine, it would be awesome to guide users to finding `chars`. What do you think of either linking to a reference table, or suggesting some interactive unix tool capturing keystrokes and returning the equivalent tty keycode? That could be part of README.md or, better, a comment in the default YAML.

Thanks.

### PR DESCRIPTION
**Pull request by ronjouch**
Am not touching the -macos yaml, as I'm not sure this works under macOS.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for the PR!

So, I think this could use a lot more explanation. You've got a bunch of context in your head about why you might want to run `showkeys -a` and in what cases you would want to run it because you've been chasing down a problem you encountered. This comment without that context is pretty confusing. Would you mind adding a bit of discussion to provide that context?

**Comment by ronjouch** [comment]
> So, I think this could use a lot more explanation. You've got a bunch of context in your head about why you might want to run showkeys -a and in what cases you would want to run it because you've been chasing down a problem you encountered. This comment without that context is pretty confusing. Would you mind adding a bit of discussion to provide that context?

@jwilm sure. My context was *"Well I'd like to bind Ctrl+PgDn to what Ctrl+PgDn is bound to in gnome-terminal, so that tmux running in alacritty reacts just like in gnome-terminal when I send Ctrl+PgDn. But I'm puzzled by these mysterious keycodes, what their name is, and have no idea how to get them"*.

So, concise expansion proposal:

```
# Want to add a binding (e.g. "PageUp") but are unsure what the X sequence (e.g. "\x1b[5~") is?
# Use `showkey -a` to get the sequence associated to your desired key combination.
```

Seems better?

**Comment by jwilm** [comment]
Yeah that would be great. Thanks!

**Comment by jwilm** [comment]
Might want to mention that you'd want to run it in another terminal like `xterm` to see what it does.

**Comment by ronjouch** [comment]
@jwilm pushed updated doc snippet with clarification and mention of xterm. I also mentioned ensuring running the other terminal without tmux. Rebased and ready to merge.

**Comment by jwilm** [comment]
Looks good; thanks!

**Pull request merged**
