### PR TITLE
Update to latest Glutin/winit

### LINKED ISSUE #234: Update Glutin
This version of glutin doesn't compile on Windows 10:
```
[dependencies.glutin]
git = "https://github.com/jwilm/glutin"
rev = "af7fe340bd4a2af53ea521defcb4f377cdc588cf"
```
Upstream glutin 0.7.1 compiles fine:
```
glutin = "0.7.1"
```

This is blocking windows support.

### PR DESCRIPTION
**Pull request by jwilm**
This *finally* gets us off the fork of Glutin we've been on for so long
and will unblock a number of other items. Functionality should be the
same as before.

Resolves #234

### CODE REVIEW

**Comment by jwilm** [comment]
Would love for others to take this for a spin before merging into master. It's been working well for me on X11 with i3wm, but it hasn't had much testing beyond that.

**Comment by jwilm** [comment]
It seems that a newer Rust compiler is required with this branch. Please update to 1.18.

**Comment by tmiller** [comment]
I don't believe this branch is working in OSX.

OS: OS X Sierra 10.12.5 (16F73)
Rust: rustc 1.18.0 (03fc9d622 2017-06-06)

screenshot 2017-07-18 11 51 17

**Comment by jwilm** [comment]
Have a patch coming for that shortly

**Comment by jwilm** [comment]
Should be fixed.

**Comment by tmiller** [comment]
Thanks, so far it looks good on OS X 👍

**Comment by monouser7dig** [comment]
works on macOS Sierra so far here as well, great terminal emulator! thanks

**Comment by Determinant** [comment]
Probably should not change directly to the latest glutin which still uses winit 0.7.0. The changes made to winit to accommodate X input method support is in the lastest master of winit.

**Comment by NickeZ** [comment]
Tried it, works for me to on Ubuntu 16.04, i3wm

**Comment by aslpavel** [comment]
Works for me with latest patches applied on MacOS Sierra 10.12.5

**Comment by jwilm** [comment]
Pushed a patch that should fix the tests. Planning to merge once travis is green.

**Comment by jonhoo** [comment]
Hmm, compiling `alacritty` takes *ages* for me now on latest nightly (currently at 1h and still going). 100% CPU usage on four cores while compiling `winit`. I'm compiling with
```console
$ cargo +nightly b --release --features nightly
```
Has anyone else seen this?

**Comment by jwilm** [comment]
That sounds very wrong. Are you trying to use incremental compilation?

**Comment by jonhoo** [comment]
Ah, right, I'd forgotten than `CARGO_INCREMENTAL` interacts poorly with alacritty. Builds fine on stable btw. I'll re-try nightly without incremental now.

**Comment by jonhoo** [comment]
Yup, works fine without incremental.

**Pull request merged**
