### PR TITLE
Conform to XDG spec for configuration

### LINKED ISSUE #203: Conform to XDG spec
Alacritty configuration should default to `$HOME/.config/alacritty/alacritty.yml` as the [XDG spec suggests](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). This is also the standard behavior for most applications. This will also help avoid environment variables being unset and introduce bugs with expected configuration file loading.

I'm also willing to open a PR for this issue.

### PR DESCRIPTION
**Pull request by 0X1A**
Use `$XDG_CONFIG_HOME/alacritty/alacritty.yml` for loading the configuration file falling back to first `$XDG_CONFIG_HOME/alacritty.yml` then finally `$HOME/.config/alacritty/alacritty.yml`

Closes #203

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for the PR! Unless I'm mistaken, this doesn't appear to fall back to the current default location of `$XDG_CONFIG_HOME/alacritty.yml`. Would you mind adding that?

**Comment by 0X1A** [comment]
@jwilm Added `$XDG_CONFIG_HOME/alacritty.yml` as the first fallback path

**Comment by jwilm** [comment]
I think the only thing this is missing would be loading from `$HOME/.alacritty`. Sorry for the delay in providing feedback.

We should also add a message about loading config from a deprecated location, but that can be done separately.

**Comment by 0X1A** [comment]
@jwilm Done, the precedence of paths is now the following:

1. `$XDG_CONFIG_HOME/alacritty/alacritty.yml`
2. `$XDG_CONFIG_HOME/alacritty.yml`
3. `$HOME/.config/alacritty/alacritty.yml`
4. `$HOME/.alacritty.yml`

**Comment by jwilm** [comment]
Thanks @0X1A!

**Pull request merged**
