### PR TITLE
Add logo SVG

### LINKED ISSUE #967: Finalize Icon Choice
We settled on using the icon from @net. In #863, some changes were discussed including using the blue flame variant, and tweaking the stroke to make it show up better on dark backgrounds.

## Tasks

- [ ] @net to tweak border
- [ ] @net to provide final SVG
- [ ] Ship icon for macOS
- [ ] Ship icon for Linux

### PR DESCRIPTION
**Pull request by chrisduerr**
This adds the SVG files for the three different versions of the
Alacritty logo to the repository. The three variations are the logo with
scanlines, without scanlines and without background or scanlines.

To unclutter the root directory of the repository a bit, every file
which is just copied to the system during the build process has been
moved into the `extra` directory. This should clean things up a bit and
allowed renaming the completions a bit to make them comply with the
default naming scheme for completions for each shell by default.

This fixes #967.

This just adds the logos which were already shown off in #967.
The goal is primarily to start the process rather than having something
which is good to go the way it is right now.

### CODE REVIEW

**Comment by chrisduerr** [comment]
@dikiaap Thanks for that! Having the wiki page ready for that is very helpful, potentially this could also be done during CI.

Currently the icon still requires a bit more work and I'm not super confident with the tools, but this should help out when the icon is repolished.

**Comment by jansol** [comment]
Looking into polishing those SVGs now. @chrisduerr could you clean up this PR so I can add on top of it instead of nuking your authorship info?

**Comment by chrisduerr** [comment]
@jansol I've rebased the PR. Thanks for offering to look into it.

**Comment by jansol** [comment]
About a build step to convert SVG to ico etc as mentioned elsewhere: would you mind adding that here or should I open an issue? (Or is that even wanted? It would in theory help with repo bloat as it removes the need to juggle binary files in the repo...)

**Comment by chrisduerr** [comment]
> About a build step to convert SVG to ico etc as mentioned elsewhere: would you mind adding that here or should I open an issue? (Or is that even wanted? It would in theory help with repo bloat as it removes the need to juggle binary files in the repo...)

I'm perfectly fine with handling everything that is not art-related myself. :D 

I'd probably opt for a build step in the ci/before_deploy.sh script, so if you want to look into that yourself (feel free to do so), you can do that there.

Note that if you have any changes you'd like to propose, it should be possible to send a PR to my branch and this PR will automatically update. I've also taken the chance and updated the assets a little bit to clean things up even further.

**Comment by chrisduerr** [comment]
@jansol Thanks a ton for helping out with this! As far as I'm concerned these icons should be good to go now.

Maybe we can still include them into 0.3.0, that would certainly work well!

**Comment by jansol** [comment]
As far as the automatic rasterization script is concerned, I personally don't want to spend time on that if possible. However I also think that it would be the right thing to do from the start.

And the sooner the icon is everywhere, the better of course :wink:

**Comment by jansol** [comment]
Also, right now only the version with scanlines has any glow and blur, if that is wanted in either of the other two versions let me know (or ape it from the scanline version yourself, it's just adjusting the blur of the relevant object group and a duplicate with even more blur for the glow)

**Comment by chrisduerr** [comment]
> Also, right now only the version with scanlines has any glow and blur, if that is wanted in either of the other two versions let me know (or ape it from the scanline version yourself, it's just adjusting the blur of the relevant object group and a duplicate with even more blur for the glow)

I think they're fine the way they are right now. At least for now. If we want to change our 'branding' in the future, we can still do that. I think the focus right now should be to get something, rather than getting the absolute best thing. This has already taken quite a long time.

**Comment by jansol** [comment]
Speaking of which, IMHO the README is the one place where the fancy scanlines version is definitely appropriate. For app icons it's debatable (at those sizes the effect is not very noticeable anyway).

**Comment by chrisduerr** [comment]
> Speaking of which, IMHO the README is the one place where the fancy scanlines version is definitely appropriate. For app icons it's debatable (at those sizes the effect is not very noticeable anyway).

I definitely agree with that and I've put the scanline version in the readme.

**Comment by lespea** [comment]
Why did this commit delete `scripts/spawn-alacritty-cwd`?

**Comment by chrisduerr** [comment]
@lespea Because Alacritty now supports that by itself with the SpawnNewInstance action.

**Comment by lespea** [comment]
Ah okay, thanks for the update!

**Pull request merged**
