### PR TITLE
Fix viewport_size.height calculation

### LINKED ISSUE #556: Alacritty ignores lines configuration
```
...
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command
  TERM: xterm-256color
# Window dimensions in character columns and lines
# (changes require restart)
dimensions:
  columns: 132
  lines: 34
# The FreeType rasterizer needs to know the device DPI for best results
# (changes require restart)
dpi:
  x: 96.0
  y: 96.0
...
```

It always boots with this output (without me resizing it):
```
num_cols, num_lines = 170, 63
num_cols, num_lines = 132, 66
```

### PR DESCRIPTION
**Pull request by N-006**
Closes #556

### CODE REVIEW

**Comment by jwilm** [comment]
Oh my, thanks for the patch!

**Comment by nicman23** [comment]
thanks was driving me insane

**Comment by jwilm** [comment]
@nicman23 sorry about that :upside_down_face: 

I've been using i3 for a while on my dev machine and it completely hid this issue.

**Comment by nicman23** [comment]
yeah i got that from the scrollback issue. I3 is my go to for small screens but sometimes i  just want compiz :P

**Pull request merged**
