### PR TITLE
clippy: fix default_trait_access warnings.

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by chrisduerr** [comment]
This looks good, thanks for sending the PR!

When testing your branch locally, since the CI build wasn't able to install Clippy, I've noticed that there a quite a few other open Clippy issues though. I think it would make sense to fix all current Clippy issues in a single PR.

**Comment by matthiaskrgr** [comment]
Ok, clippy works again and I added fixes for most of the trivially_copy_pass_by_ref cases.
There was one which I was not able to fix though, involved in macro code:
````
    Checking alacritty v0.1.0 (file:///home/matthias/vcs/github/alacritty)
error: this argument is passed by reference, but would be more efficient if passed by value
   --> src/index.rs:286:28
    |
286 | fn steps_add_one_u8(start: &u8, end: &u8) -> Option<usize> {
    |                            ^^^ help: consider passing by value instead: `u8`
    |
note: lint level defined here
   --> src/lib.rs:16:44
    |
16  | #![cfg_attr(feature = "cargo-clippy", deny(clippy, if_not_else, enum_glob_use, wrong_pub_self_convention))]
    |                                            ^^^^^^
    = note: #[deny(trivially_copy_pass_by_ref)] implied by #[deny(clippy)]
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.210/index.html#trivially_copy_pass_by_ref
````

**Comment by chrisduerr** [comment]
I swear I've fixed some of these clippy issues in the #1373 PR, but I can't find it right now.

I'm pretty sure this macro can be fixed by replacing every instance of &u8 or &T in the macro with u8 or T. I could also fix this myself, whatever you prefer. I'm happy to help out if you want to take a stab at it. But generally I think nothing the macro is used for needs a pass by reference, because it's all `Copy`.

**Comment by chrisduerr** [comment]
Oh yeah, I'm so sorry for making you do all the work I've done again, but it looks like I've fixed the Clippy issues in here already: https://github.com/jwilm/alacritty/pull/1387/commits/a4db0556c44c5b50ce2dffa1d6aaf0c9546724a0.

I would prefer a separate PR though, so I'd like to add the changes that are missing to this PR and then just rebase #1387 once this is merged. Would you be willing to do this? I don't care about having these change attributed to me, so just copy/pasting the code would be fine if you don't want to mess with git.

**Comment by matthiaskrgr** [comment]
Hm, I checked out #1387 and it seems that no clippy warnings are left :)
I'm going to close this one.

**Comment by chrisduerr** [comment]
Oh okay, sorry  for causing the work duplication, but it's still much appreciated!

It can get a bit messy with the amount of PRs I've currently open.

**Pull request closed without merging**
