### PR TITLE
Use correct keyname for decreasing font size in MacOS 

### PR DESCRIPTION
**Pull request by enilsen16**

### CODE REVIEW

**Comment by asilvadesigns** [comment]
@enilsen16 thanks!

**Comment by weslly** [comment]
It would also make more sense to use `command` instead of `control` at the modifier for macOS, like iTerm2 and Terminal.app.

**Comment by jwilm** [comment]
@enilsen16 thanks for the PR! Great point @weslly; would you mind including that here @enilsen16?

**Comment by enilsen16** [comment]
Updated

**Comment by jwilm** [comment]
thanks!

**Pull request merged**
