### PR TITLE
Add option to draw borderless windows

### PR DESCRIPTION
**Pull request by robertgzr**
Partial solution for #168 until winit has more granular control over the window decorations https://github.com/tomaka/winit/issues/323

### CODE REVIEW

**Comment by sodiumjoe** [comment]
Just tried this out locally, it appears to make the window unresizeable.

**Comment by sodiumjoe** [comment]
It appears to be an issue with the winit borderless option, as I can reproduce this with the window example in winit by adding the `.with_decorations(false)` and running it.

**Comment by robertgzr** [comment]
@sodiumjoe are you on macOS as well?

**Comment by sodiumjoe** [comment]
@robertgzr yes I'm on macOS Sierra 10.12.6.

**Comment by robertgzr** [comment]
@jwilm 
I changed things according to your comments. 
I moved `dimensions` and `padding` into the new `window_config` along with the renamed `decorations` option (this could later be used for tinting the titlebar dark if that gets implemented)

**Comment by anxiousmodernman** [comment]
I was just wanting this feature, and came across this PR. I built it and it works great. If possible, it would be convenient to be able to remove decorations with a flag `--decorations false` or similar.

**Comment by sodiumjoe** [comment]
hm, am I the only one unable to resize windows without the decorations?

**Comment by anxiousmodernman** [comment]
Resize via mouse is not possible without the borders, I think. But on most linux environments one can access the context menu anyway via `alt+space`. Minimize, maximize, resize, and move can be done from there, albeit in a clumsy way. I just usually maximize.

**Comment by robertgzr** [comment]
@sodiumjoe 
I am on macOS as well (10.11.6) and resizing the window doesn't work.
Even with [hammerspoon](http://www.hammerspoon.org/) I get errors...

**Comment by sodiumjoe** [comment]
@robertgzr Yeah, I'm a hammerspoon user too, and I would be totally fine if I could resize with hammerspoon, but this feature is pretty useless without any way to resize.

**Comment by monouser7dig** [comment]
I am on macOS as well but the title bar is still there, put `decorations: false` in the local `alacritty.yml` as well as the one in my .config dir but both had no effect.
Otherwise, sounds great.

**Comment by jwilm** [comment]
Looks good @robertgzr. I added a couple more commits so that we don't break existing config setups. Waiting on travis now.

**Comment by jwilm** [comment]
Problems resizing without decorations is probably a winit issue. We can track that separately if needed.

**Comment by robertgzr** [comment]
@jwilm 

I got the fix for being unable to move borderless windows on macOS merged in https://github.com/tomaka/winit/pull/382

It's implemented as a platform specific extension to `WindowBuilder`. How would we make use of this in alacritty? [Like that...?](https://github.com/jwilm/alacritty/blob/master/src/window.rs#L315)

**Comment by sodiumjoe** [comment]
@robertgzr Super excited about this work! I tried this out locally by using local dependencies on glutin and winit, and hardcoding the builder settings i want, and it looks great on my primary laptop screen, but it looks like there are some weird issues with dpi or something. When I open an alacritty window on an external monitor:

screenshot 2018-01-26 10 51 46

As you can see, everything is rendered too small, and only in one quarter of the window. This is what it looks like if I resize up a few times:

screenshot 2018-01-26 10 53 25

here's the diff for `src/window.rs`

```rust
➤ git diff src/window.rs
diff --git a/src/window.rs b/src/window.rs
index 55b7cd5..5ce82ab 100644
--- a/src/window.rs
+++ b/src/window.rs
@@ -16,9 +16,9 @@ use std::fmt::{self, Display};
 use std::ops::Deref;

 use gl;
-use glutin::{self, ContextBuilder, ControlFlow, CursorState, Event, EventsLoop,
+use glutin::{self, ContextBuilder, ControlFlow, CursorState, Event, EventsLoop, GlContext,
              MouseCursor as GlutinMouseCursor, WindowBuilder};
-use glutin::GlContext;
+use glutin::os::macos::WindowBuilderExt;

 use MouseCursor;

@@ -195,9 +195,11 @@ impl Window {

         Window::platform_window_init();
         let window = WindowBuilder::new()
-            .with_title(title)
+            .with_title_hidden(true)
             .with_visibility(false)
             .with_transparency(true)
+            .with_fullsize_content_view(true)
+            .with_titlebar_transparent(true)
             .with_decorations(window_config.decorations());
         let context = ContextBuilder::new()
             .with_vsync(true);
```

**Comment by sodiumjoe** [comment]
The other thing this brings up is it would be nice if the `padding` config were `top`, `bottom`, `left`, `right`, instead of just `x` and `y`, since the transparent/hidden titlebar basically becomes part of the padding.

**Pull request merged**
