### PR TITLE
Add hidden escape sequence

### LINKED ISSUE #1454: Hidden escape sequence
The `\e[8m` escape sequence should set the foreground color of the text to the background color. Currently this escape sequence is completely ignored.

**Note:** It is not enough to set the hidden color to be the exact same as the normal background color, since hidden text should also be hidden on different background colors.

See https://misc.flogisoft.com/bash/tip_colors_and_formatting for additional documentation.

### LINKED ISSUE #1455: Invert escape sequence incorrect
The command `echo -e "Normal \e[101;91mTest \e[7mInverted"` will print `Inverted` with the default foreground color as background and the default background color as foreground.
The correct behavior would be to print it the same as `Test`.

This bug is due to the following code:
https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L385-L389

### PR DESCRIPTION
**Pull request by chrisduerr**
This adds support for the `hidden` escape sequence `\e[8m`, which will
render the text as invisible.

This has also raised a few questions about the rendering of foreground
and background colors and their interaction with the different escape
sequences. Previously, Alacritty has oriented itself after URxvt, which
has some strange and unexpected behavior.

The new implementation of color inversion is modeled after XTerm, which
has a consistent pattern of always inverting the foreground and
background colors. This should hopefully lead to less confusion for the
user and a more consistent behavior.

A full matrix showcasing the new way Alacritty inverses text can be
found here:
https://i.imgur.com/d1XavG7.png

This fixes #1454 and fixes #1455.

@jwilm you've mentioned that things were implemented this way for a reason,
modeling Alacritty after URxvt and allowing transparency to work properly.
I'd be interested to hear what you think about the changes to color inversion,
I'd say this is a pretty clear improvement because it makes things a lot more
consistent.

### CODE REVIEW

**Comment by jwilm** [comment]
Wow, nice work! I'm a bit conflicted on modelling after xterm vs urxvt. One one hand, xterm is the standard, but in practice, many use emulators like urxvt or those based on libvte. The debate is about whether to match an actual standard vs expected behavior.

Would you mind posting a few more screens? Specifically, it would be nice to see Alacritty, urxvt, xterm, and a libvte-based emulator like gnome-terminal all with transparency. If you don't have these setup, maybe don't worry about it since it would be a bit onerous.

**Comment by chrisduerr** [comment]
Oh yeah sure, I'll post a few more screenshots for comparison.

I'd actually say XTerm's behavior here is a lot more coherent than URxvt's, which seems almost arbitrary at some points.

**Comment by chrisduerr** [comment]
Okay, I've made a few more screenshots for comparison. I've fully configured Termite, which is VTE-based and it seems to match Alacritty and XTerm. The only difference is that it seems to support inverting the background to foreground and I'd actually say that Alacritty does something wrong here. Even though it should be unrelated to my changes, I'll take a look if there's an easy fix.

Here's the comparison:
### Alacritty


### Termite


### URxvt

**Comment by chrisduerr** [comment]
Rebased and confirmed to be working using the included script. Everything should still be good.

**Pull request merged**
