### PR TITLE
Implement copypaste/x11 using x11-clipboard

### LINKED ISSUE #5: Native clipboard support on X11 and Wayland
The biggest issue I've been having with alacritty recently is pasting from the clipboard. Copying would be nice to, but apparently pasting comes up _a lot_.

### PR DESCRIPTION
**Pull request by quininer**
fix #5

### CODE REVIEW

**Comment by brycefisher** [comment]
@quininer this looks awesome!

@jwilm -- any thoughts on this PR? I know you were concerned about reusing Servo's clipboard library due to the GPL license. It looks like @quininer has written [x11-clipboard](https://crates.io/crates/x11_clipboard)  for use in Alacritty under an MIT license (that's just me speculating).

**Comment by dvergeylen** [comment]
@quininer, I guess this PR can be updated to x11-clipboard 0.2.0 you released in July?

@jwilm could you find time to inspect this PR? Not needed for 1.0 milestone but might useful nonetheless ;-)

**Comment by bitemyapp** [comment]
I fixed this up for merge cleanliness here: https://github.com/bitemyapp/alacritty/tree/clipboard

Not sure if I did it right though.

**Comment by jwilm** [comment]
> Not sure if I did it right though.

Do both copy/paste targets work as they do on master? Would love to land an up-to-date version of this PR.

**Comment by bitemyapp** [comment]
@jwilm copy and paste (as in, highlight -> middle click) do not work in master.

It works when I use the branch I created. I just re-tested with two processes side-by-side and a brower highlight of this text to be sure.

screenshot from 2017-10-10 17-33-15

The first line, "I just re-tested..." is because the highlight in the `master` built alacritty process didn't inject the highlighted text into my copy-paste buffer.

**Comment by jwilm** [comment]
@bitemyapp master requires xclip to work properly; guessing that's missing on your system. That said, sounds like this is in a good place.

**Comment by bitemyapp** [comment]
@jwilm good place meaning it will or won't get mainlined?

In the case of the latter: https://github.com/jwilm/alacritty/compare/master...bitemyapp:clipboard makes it look like it axes an unfortunate dependency on calling out to a foreign process and simplifies the code in the process. Is there a potential downside I am missing?

**Comment by jwilm** [comment]
Oh yeah, I definitely want to land this. I just need to find a bit of time to test and merge. On travel this week so hopefully this weekend.

**Comment by bitemyapp** [comment]
@jwilm thank you! Just tested on macOS, cmd-c and cmd-v seemed to work fine.

**Comment by chetgurevitch** [comment]
Looks like this is good to go w/ x11-clipboard v0.2.2, there's just a small merge conflict with 5f7885749c4d7e48869b1fc0be4d430601cdbbfa due to a dropped mut.

**Comment by jwilm** [comment]
I tested this out recently and ran into an issue pasting a selection into vim with <kbd>"</kbd>, <kbd>*</kbd>, <kbd>p</kbd>. Previously, this pasted the selection buffer, but now nothing happens. This works fine in other terminal emulators and the current master of Alacritty but not this branch.

**Comment by chetgurevitch** [comment]
Hmm, seems you're correct. Opened https://github.com/quininer/x11-clipboard/issues/8.

**Comment by maximbaz** [comment]
FYI I've just tried out this branch and pasting from the selection register works fine, with or without tmux - I tested in neovim v0.2.2, and I haven't uninstalled `xclip` as it is still a required dependency for other apps that I have.

**Comment by chrisduerr** [comment]
I've also tested this in normal vim, which behaves a bit differently than neovim with scrollback. I've already talked with @jwilm about this on IRC and he's probably gonna take another look sooner or later.

**Comment by chrisduerr** [comment]
@quininer I'd like to thank you a lot for your work on the x11-clipboard crate. Based on my testing this all worked great, however I'm not sure if I want to keep maintaining the `copypasta` crate now that `clipboard`'s licensing issues have been resolved. I think it would make sense to try and make use of one clipboard library for Rust instead of duplicating the effort.

I'll keep https://github.com/jwilm/alacritty/issues/5 updated with progress made on this effort, hopefully this will enable us to finally achieve native clipboard support on all platforms.

**Pull request closed without merging**
