### PR TITLE
Add terminal window padding support

### LINKED ISSUE #343: Inner Borders like rxvt-unicode
I like to know if there is a way to add inner borders aka padding like in rxvt-unicode or vte terminals with gtk.css.

### PR DESCRIPTION
**Pull request by siiptuo**
- [x] Basic support
- [x] Add configuration
- [x] Fix underflow error

Fixes #343

### CODE REVIEW

**Comment by siiptuo** [comment]
Regarding the default padding: should it have some smart default as discussed in the issue? If so, should it be based on font metrics or simply font size?

**Comment by buger** [comment]
I would recommend you not to update configration scheme, because it is not backward compatitable. Making padding a root variable, will make more sense in this case. And probably what is more important will make merging this PR totally safe.

```
dimensions:
  columns: 80
  lines: 24

padding: 2
```

**Comment by jwilm** [comment]
@buger config layout is not going to be stable until 1.0.

**Comment by buger** [comment]
Sure, it's up to you.

Just wanted to help this get merged, because I want it :)

**Comment by hhsnopek** [comment]
@jwilm any idea on when this will be dropped or what's holding it back? 😀

**Comment by jwilm** [comment]
The only thing holding it back is my time (which should become more abundant in April). Since this PR is smallish, I'll make time to review it sooner. Sorry.. just been busy ;)

**Comment by jwilm** [comment]
Closing this in favor of #543.

**Pull request closed without merging**
