### PR TITLE
OSX: Add app packing tooling - tweaks and polish

### PR DESCRIPTION
**Pull request by brycefisher**
Continuation of work started in https://github.com/jwilm/alacritty/pull/301 by @cema-sp which seems to be stalled at the moment. I've just followed all the suggestions in that PR until the code worked for me.

Instructions for building an app bundle:

 1. `cargo build --release`
 2. `make app`
 3. `cp -r target/release/os/Alacritty.app /Applications/Alacritty.app`

For me, this allows me to run Alacritty from the Dock.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for trying to move this along! The only reason I haven't landed this yet is because the instance of Alacritty opened from this launcher is broken for me. The shell launches with `PWD=/`, and programs like vim are horribly broken (probably PATH and vimrc/config related).

Any thoughts on that?

**Comment by mondras** [comment]
@brycefisher Not sure if something's broken on my end but after following the instructions I still get the `LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Alacritty.app.` error

@jwilm if I open this with `./target/release/osx/Alacritty.app/Contents/MacOS/launcher` my pwd is `~`, happy to help fix the bug if I can reproduce it first!

**Comment by jwilm** [comment]
If you install the launcher to your /Applications folder and run it from the launcher, you should see the problem.

**Comment by jwilm** [comment]
er, install Alacritty.app to the /Applications folder

**Comment by philipp-spiess** [comment]
When I start alacritty with this mac launcher, I see no unicode special characters inside a tmux session (but all works fine without the tmux session). This does not happen when I run the binary via shell.



Any ideas what could cause that? [Here's my current config](https://github.com/philipp-spiess/dotfiles/blob/master/.alacritty.yml)

**Comment by mondras** [comment]
I was able to launch it @brycefisher ! My bad, I guess I screwed up before.

And @jwilm I just opened directly through `/Applications/Alacritty.app` and... PWD is home. Maybe this actually helped fix that problem: https://github.com/jwilm/alacritty/pull/462/commits/018beee8b65e2c69f0145d33dc7dc50db5aac4cf

Are you still getting that behavior in this branch?

**Comment by jwilm** [comment]
Ah that does seem to be fixed on this branch. The other problem I'm seeing is that the LANG and LC_CTYPE environment variables aren't being set appropriately from Alacritty.app.

After running

```bash
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```

Everything works as expected.

**Comment by philipp-spiess** [comment]
@jwilm I can confirm that the language settings were also the root of the problem I described above. 👍

**Comment by jwilm** [comment]
It looks like iTerm gets around this by actually using the OS APIs to read the system locale.

**Comment by brycefisher** [comment]
Glad the lang issue resolved themselves before I was even aware of what they were!

@jwilm do I need 

```sh
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```

to launcher.sh?

**Comment by jwilm** [comment]
@brycefisher unfortunately no. We need to actually query [NSLocale](https://developer.apple.com/reference/foundation/nslocale).

**Comment by brycefisher** [comment]
@jwilm should that work happen inside this PR?

**Comment by casimir** [comment]
You can also get it with AppleScript, something along `osascript -e "return user locale of (get system info)"`.

**Comment by brycefisher** [comment]
I've incorporated @casimir's feedback into this PR, but I'm not sure of all the edge cases that need to be covered here (ex: if AppleScript doesn't return a locale under some conditions, or what versions of OSX support that AppleScript snippet, or if I should not be hardcoding UTF-8).

**Comment by brycefisher** [comment]
@jwilm any other issues I should address in this PR?

**Comment by jwilm** [comment]
@brycefisher I don't think so, thanks for driving this home! (I'll merge later)

It would be *really* nice if we had a config Action for running arbitrary commands. Then on macOS we could add a Cmd+N binding for launching more Alacritty instances. Otherwise, the launcher is only good for one instance.

Fancy tackling that in another PR? :D

**Comment by mondras** [comment]
🎉 !

@jwilm I'd like to help routing shortcuts to the OS like Cmd+Q for closing, but honestly have no idea on where to start. With a bit of direction I can get it started.

**Comment by brycefisher** [comment]
@jwilm hooray! So excited to have this this excellent work from @cema-sp land in master.

I'd love to see that work for MacOS shortcuts happen, but I'd happily leave it to @mondras since I too have no idea where to start.

**Comment by jwilm** [comment]
Thanks again for pushing this forward and fixing the outstanding issues. Happy to include this finally :grin:

**Comment by dvcrn** [comment]
This is fantastic! Thanks for the great work guys!

**Pull request merged**
