### PR TITLE
Update to glutin 0.16.0

### LINKED ISSUE #148: Compose key does not work
A chiefly x11 feature called compose keys does not work with alacritty.

### LINKED ISSUE #372: Glutin reports wrong KeyboardInput for modifier keys
I don't know if this is a general problem with glutin or specific to the fork used in Alacritty: The KeyboardInput-events only report `LAlt` / `LControl` / `LWin`, even if the right modifier key is pressed. Since some special characters like `|` can only be reached via the right modifier keys on my keyboard-layout, I can't produce characters like `|` in Alacritty.

Running Darwin Kernel Version 16.3.0 with glutin 0.6.1 (git+https://github.com/jwilm/glutin?rev=af7fe340bd4a2af53ea521defcb4f377cdc588cf)".

> glutin event: KeyboardInput(Released, 62, Some(LControl), , None)
> glutin event: KeyboardInput(Pressed, 61, Some(LAlt), , None)
> glutin event: KeyboardInput(Pressed, 54, Some(LWin), , None)

### LINKED ISSUE #764: Quotes, double-quotes, sharp accents are not working
pressing quotes/doublequotes/sharp accents is not working for me :(

### LINKED ISSUE #830: thread 'main' panicked at 'XOpenIM failed'
Which operating system does the issue occur on?
`Linux gurdit-lp 4.9.31-1-MANJARO #1 SMP PREEMPT Wed Jun 7 19:39:15 UTC 2017 x86_64 GNU/Linux`

If on linux, are you using X11 or Wayland? `X11`

I followed the installation instruction of arch linux as specified in the readme. The installation completed with no errors. But when I try to execute `alacritty` from my old terminal. I get this error
```
thread 'main' panicked at 'XOpenIM failed', /home/gurditsbedi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Now I run again `alacritty` after executing `export RUST_BACKTRACE=1` and I get this.
```
thread 'main' panicked at 'XOpenIM failed', /home/gurditsbedi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>
```

### LINKED ISSUE #1041: Cannot input characters with dead keys
Which operating system does the issue occur on?
MacOS 10.13.2

I cannot input characters requiring dead keys (e.g. with US International layout ñ or é or even " ). After pressing the dead key nothing happens. The next character is just printed normal.

### LINKED ISSUE #1185: Weird scrolling behavior
I've noticed weird janks when scrolling from the beginning I use alacritty but I wasn't sure what are the reliable steps. Now I'm able to reproduce it on 100%. I'm using i3-wm so it can be related to combination of i3, tmux & alacritty. It doesn't happen in xfce4-terminal with tmux though.

Steps:
1. open alacritty on one workspace, open Chromium on another workspace
2. open tmux and vim inside tmux with some long file, scroll in the middle of the file
3. open some long page in Chromium
4. switch to alacritty, scroll up, scroll down, remember the line and notice that scrolling is working fine
5. switch to Chromium a scroll up for some time (few page, for example)
6. switch back to alacritty and trigger single scroll down or up and notice that scrolling move several lines/pages up

It seems to me that alacritty is not handling properly focus & blur events so when I scroll in another window in the system and get back to alacritty and trigger scroll it will replay all the scroll events which happened while alacritty was in the background (blurred).

My tmux config:
```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc" # See https://github.com/tmux/tmux/issues/34
set -g mouse off
set -g history-limit 100000
set -s escape-time 0
set-option -g status off
set-window-option -g xterm-keys on

bind-key m set-option -g mouse off
bind-key M set-option -g mouse on

bind-key [ copy-mode \; send-keys 0 \; send-keys H

run-shell ~/.files/tmux/plugins/extrakto/extrakto.tmux
```

Arch Linux 4.15.8-1-ARCH x86_64 with X11
xorg-server 1.19.6
mesa 17.3.6
i3-wm 4.14.1-2
tmux 2.6

### PR DESCRIPTION
**Pull request by francesca64**
Note that `WM_CLASS` is now set to `"alacritty", "Alacritty"` instead of the previous value of `"Alacritty", "Alacritty"`. This seems to be more standard.

This also contains some revised recommendations for installing the `.desktop` file.

Fixes #148
Fixes #372
Fixes #764
Fixes #830
Fixes #1041 
Fixes #1185

### CODE REVIEW

**Comment by chrisduerr** [comment]
Awesome! Thanks a lot for this PR, looks like it solves a bunch of long-standing issues.

**Comment by jwilm** [comment]
Thanks, @francesca64!

I've said it before and I'll say it again -- I have immense appreciation for the work you're doing on winit. I've lost track by now of how many bugs you've fixed that directly improve Alacritty, and that's completely discounting all of the ongoing logistical and architectural improvements you've made or have in the works. This is a big deal not only for Alacritty but also the Rust ecosystem of GL applications for which there are countless users. There are few others that are having nearly the impact that you do.

You have my gratitude; thank you.

:bowing_man:

**Comment by francesca64** [comment]
Thanks so much! I've been trying to pace myself more to ensure that I don't get burned out, so with some luck the progress will continue for a long time.

**Comment by chrisduerr** [comment]
Please do! (Pace yourself, not get burned out)

**Pull request merged**
