### PR TITLE
Fix SGR mouse reporting, report middle and right mouse and report modifiers

### LINKED ISSUE #1142: Mouse input doesn't work
**Which operating system does the issue occur on?**
Void Linux

**If on linux, are you using X11 or Wayland?**
X11

**Which version of Alacritty?**
Master (f298ebb2179eff947cdb9cb7a4bd96e9739eac5c)

Applications which accept mouse input either don't react at all or react in a broken way. For example: [Cmus](https://cmus.github.io/) and [Ranger](https://github.com/ranger/ranger); both support mouse input for selecting items in their interfaces but this doesn't work in a *bare* Alacritty terminal. However, running tmux inside Alacritty and using any mouse-enabled application through tmux, mouse input works perfectly fine.

It seems Alacritty *is* sending input, but *incorrect* input? In Neovim, with mouse input enabled, clicking a line shows `23m` in the command window in the bottom right (where "23" corresponds to the line being selected). And does nothing else. 

What's strange is I've been using Alacritty for about 3 weeks and I had this problem when I first installed it, but it went away after a few days and I have no idea what changed. Alacritty's been working fine until a few days ago and, again, I have no idea what changed.

Oh and for comparison, xterm works as expected on my machine (without tmux).

### PR DESCRIPTION
**Pull request by chrisduerr**
There was an issue with mouse clicks not working inside of htop which
was caused by incorrect SGR mouse reporting.

With normal mouse reporting the button codes 0/1/2 are used to indicate
which button has been pressed and button code 3 is used to indicate that
any button was released.

However in SGR mode the button codes are always 0/1/2 even when the
mouse is released (this is instead indicated through m/M at the end).

Alacritty was sending button code 3 whenever the mouse has been released
even in SGR mode, which is incorrect.
This has been fixed by only overwriting the button code on release
inside the normal mouse handling and always passing the exact button
code for mouse handling in general.

There were also a few inconsistencies with xterm.
In xterm before any mouse interaction is allowed, the normal mouse flag
always has to be set. If only SGR or MOUSE_MOTION is enabled, without
the normal mouse mode, nothing should happen.
When an application enables multiple things at once ([1006, 1000]), xterm
also enables both, alacritty only attempts to enable the first and uses
the second one as fallback.

Alacritty now adds all modes in the args array whith the 'h' flag and
removes all modes inside the array with the 'l' flag.
It also doesn't do anything with mouse motion or sgr mouse unless the
normal mouse support is also enabled.

This fixes #1142.

### CODE REVIEW

**Comment by chrisduerr** [comment]
The latest change contributes two changes:

- Mouse should work in vim/tmux again
- Mouse modifiers should be reported

However mouse modifiers will still not work because xterm's terminfo does not allow for the `ctrl` modifier key. Alacritty will probably have to get its own termconfig, however when switching to something else like `rxvt-unicode-256color`, it should already work.

**Comment by chrisduerr** [comment]
While I'm already at it I've also included reporting for middle and right mouse button.

This should not introduce any regression but some more testing might be needed.

**Comment by NickeZ** [comment]
I've had an issue that neovim sometimes scrolled down all the way to the bottom when I scrolled a single step. I think this has solved it! I cannot reliably reproduce the issue though so I will have to test for a few days.

**Comment by chrisduerr** [comment]
If it still exists, please create an issue for it. I don't think I've heard that one before.

**Comment by NickeZ** [comment]
Sure if I notice it again I can report it. But I don't feel very helpful reporting a bug that I cannot reproduce reliably. I think I saw a report once about it somewhere but I can't find it now. Maybe it wasn't in an issue but on reddit or somewhere else..

I think you might have solved multiple reported issues with this PR. Here are a few mouse related:

https://github.com/jwilm/alacritty/issues/433
https://github.com/jwilm/alacritty/issues/714
https://github.com/jwilm/alacritty/issues/803

**Comment by chrisduerr** [comment]
Seems like I've accidentally reimplemented #1057 :)

Maybe we can put these two together.

**Comment by chrisduerr** [comment]
I'm going to send a PR to @Celti in #1057 to merge these two PRs together.

**Pull request closed without merging**
