### PR TITLE
Update glutin, bitflags and other dependencies

### LINKED ISSUE #758: Alacritty opens as a tiny spec in a corner
See the attached screenshot. I'm using the current master (b92ba65) on archlinux + gnome with the default config file. 

screenshot from 2017-08-27 10-26-32

1. Window is a tiny spec in the top left corner
2. Title is 'Unknown'
3. Icons are broken 
4. No icons to maximise/minimize or close the window

### PR DESCRIPTION
**Pull request by chetgurevitch**
Vastly improves wayland support. Only one line had to be added in event.rs to pass on an additional case in a match statement. I also removed minor version numbers specified in Cargo.toml so we always use the latest compatible versions. Every dependency is on the latest version (major and minor) with the exception of bitflags. They recently pushed version 1.0 but haven't published any release notes about the breaking changes.

Edit: Closes #758 and #702.

### CODE REVIEW

**Comment by chetgurevitch** [comment]
Updated more dependencies, including bitflags. Also integrated #777, #778 and #799. Temporarily switched to my fork of winit, which can be removed once winit hits 0.8.3. Over at https://github.com/chetgurevitch/alacritty/tree/scrollback I've also integrated #657 and #522. I didn't include the clipboard change b/c for some reason it breaks pasting into firefox, which needs further investigation.

**Comment by ibotty** [comment]
Any progress?

**Comment by chetgurevitch** [comment]
Yeah, this has been good to go for quite a while now though I've added to it over time. Non-breaking updates are all in the first commit and others were broken out. 

I'd appreciate it if @jwilm could take a look at this, especially before merging #777 to avoid duplication of work. I dropped #778 and #799 since they were merged upstream and transfered the necessary changes into the bitflags commit last night and everything passed on travis, it's only running again b/c I just did another cargo update.

Also @jwilm if you could update the freetype-sys dependency in https://github.com/jwilm/libfontconfig to 0.6 we could bump freetype-rs and core-graphics would be the only outdated dependency in the whole project, which I left on version 0.9 b/c the other core- crates haven't been updated yet and it'd just get duplicated anyways.

Finally if this is merged we can integrate my changes back into #657, which I've already rebased on top of all the changes in master and this PR.

**Comment by jwilm** [comment]
Hey @chetgurevitch,

Thanks for your patience here. I'm actually waiting to get a winit issue fixed on macOS. Last time we tried to update, it broke alacritty. #818 has details.

**Comment by chetgurevitch** [comment]
@jwilm we determined that the winit update itself wasn't what broke alacritty but rather the other changes in that pr and macos users confirmed this branch worked. It was decided that the scope of those changes was upstream rather than in alacritty, so @vberger has been working hard on updates to wayland-rs and winit, but none of those are included in glutin The changes included in this PR do not include those that caused and are relevant to #818.

**Comment by vberger** [comment]
@jwilm Yes, I'm pretty sure the reason my earlier PR broke MacOS was probably due to [this change](https://github.com/vberger/alacritty/commit/be0543ea41ceeeb098fba19d86c0d713bbc64c70#diff-2ce3f8d26915325bbd02de9e0056281eR260) for which I didn't properly consider the cross-platform implications, and not the winit upgrade itself

**Comment by jwilm** [comment]
Thanks for the clarification @chetgurevitch and @vberger.

@chetgurevitch in that case, this should be good to go; however, I would like to land #777 separately so the author has the PR show up as merged rather than closed. Would you mind backing that out?

**Comment by chetgurevitch** [comment]
@jwilm #777 has an incompatibility with the bitflags update. I can integrate that specific change into the bitflags commit but you'd have to merge #777 first.

**Comment by chetgurevitch** [comment]
@jwilm If #777 and #865 both look good to you I think the best path forward would be to merge them upstream after which I can drop #777 and fix the bitflags issues here. I skimmed through the open pull requests and I think scrollback should be the only other one affected.

**Comment by myfreeweb** [comment]
With these updates, instead of starting up as a 0x0 window with only the border visible, it starts up with the window contents being out of bounds :D

wayland-screenshot-fs8

(becomes normal after resizing)

**Comment by jwilm** [comment]
I ended up just running cargo update separately instead of trying to decouple this PR from all of the other commits.

**Comment by jwilm** [comment]
I guess technically that didn't update anything majorly like winit. Filing an issue for it to be done separately.

**Comment by chetgurevitch** [comment]
@jwilm everything that could be done with cargo update _was_ done in a single commit, the other commits all required changes to source. I bundled #777 in here while I was waiting for it in master since the bitflags update effected it but I can add those changes to the bitflags commit now that it has been merged.

**Pull request closed without merging**
