### PR TITLE
Enable live dpi toggling

### PR DESCRIPTION
**Pull request by chrisduerr**
This change makes it possible to enable/disable DPI scaling during runtime on
all platforms.

### CODE REVIEW

**Comment by chrisduerr** [comment]
@sodiumjoe I'd be interested to hear what you think about this. I haven't tested it on MacOS but it should work. If anyone is able to test, that would be nice.

This should allow updating DPR at runtime and make it easier, do you think you can rebase on #1346 on top of this @sodiumjoe or will this method of updating the DPI scale not work with your implementation?

**Comment by elzii** [comment]
@chrisduerr 

importantperiodicasianwaterbuffalo-size_restricted

Here's a crappy screen recording I did to show what happens for me when running on macOS and toggling airplay casting AirPlay on/off (same effect as unplugging/plugging into an external monior with different DPI, in this case).

The first alacritty build is master, the 2nd is from this PR. No difference observed.

**Comment by chrisduerr** [comment]
I'm not quite sure what I'm looking at here.

**Comment by elzii** [comment]
@chrisduerr At starting screen:

* Top left is stable alacritty build
* Bottom left is this PR build
* Right is sublime text for an example of scale

When plugging into monitor:

* Sublime text stays in scale (expected)
* Alacritty stable build scales up (expected bug)
* Alacritty PR build scales up (unexpected, this aimed to resolve)

Does that help? Sorry, the windows shift places so i makes it a little confusing.

**Comment by chrisduerr** [comment]
The main goal of this PR is just to make it possible to enable/disable DPI scaling, the automatic scaling when moving a window across monitors is just a side-effect that works at least on x11.

I'm not very familiar with how things work on macos though, but have you tried out #1346?

**Comment by elzii** [comment]
My mistake! I started on this venture from that PR.

**Comment by chrisduerr** [comment]
This PR has been merged together with #1403.

**Pull request closed without merging**
