### PR TITLE
Move rust dependency to the Prerequisites section

### PR DESCRIPTION
**Pull request by maximbaz**
Better fix for #718.

### CODE REVIEW

**Comment by jwilm** [comment]
Hey, thanks for the update on Arch Rust dep. I was trying to avoid calling out a specific compiler version in the README to allow the minimum version to change without having to update docs. Do you think we should go back to specifying a version?

**Comment by maximbaz** [comment]
Well it was defined on step 3, I merely moved it upwards 🙂 Good point, how would you phrase it?

**Comment by jwilm** [comment]
Oh, I somehow missed that. "Most recent stable Rust compiler" is probably the phrasing we want.

**Comment by maximbaz** [comment]
Done 🙂

**Comment by jwilm** [comment]
Thanks!

**Pull request merged**
