### PR TITLE
Remove the launcher and set the locale/current directory in alacritty

### PR DESCRIPTION
**Pull request by tbodt**
This fixes all the weirdness where opening the app bundle would start one copy which immediately disappeared and then start another copy, etc. The code to get the locale probably should be reorganized.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for the PR! This looks good, but for some reason Alacritty.app no longer shows a window when I try and use it. Any idea?

**Comment by tbodt** [comment]
I ran into that too. Changing the bundle ID in the info.plist fixed it for me, so I assumed it was just something about the launch services cache. Maybe it is. `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill` would clear it.

**Comment by jwilm** [comment]
Not sure if this was a problem before, but doing `open -n -a /Applications/Alacritty` seems to trigger that behavior when an Alacritty is already open.

**Comment by tbodt** [comment]
I suspect that's because macOS apps aren't generally supposed to have multiple instances open. Will investigate.

**Comment by jwilm** [comment]
This is kind of getting into the multiple windows territory, but it would be nice if we could support it easily. For instance, I can setup a keybinding like 

```yaml
  - { key: N,        mods: Command, command: { program: open, args: ['-n', '-a', '/Applications/Alacritty.app'] } }
```

to open new instances, but it doesn't matter if they don't show up. 😆 

In any case, maybe this problem is nothing new with your PR and it has always been a problem.

**Comment by tbodt** [comment]
Yeah, changing the bundle ID to io.alacritty and removing the launcher seems to trigger this on all versions of alacritty. This is kinda weird though.

**Comment by luceat-lux-vestra** [comment]
I solved #668 by deletes all of `supporting files`(CleanMyMac's term).

Actually, I deleted these two locations.
`~/Library/Saved Application State/com.jwlim.alacritty' (CFBundleIdentifier which you gave to alacritty)
`/private/var/folders/**some randome places**/com.jwlim.alacritty`

I don't know what's in there exactly.
But it solves `doesn't show up` issue.

**Comment by tbodt** [comment]
ooh, it's really good to know that deleting Saved Application State fixes it. one of those features that apple enabled for everyone including people who really don't want it.

**Comment by tbodt** [comment]
Moving this to a new PR so that I can do more interesting stuff on my master branch. #879

**Pull request closed without merging**
