### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by schrepfler**

### CODE REVIEW

**Comment by chrisduerr** [comment]
All installation instructions omit the `sudo` intentionally, to keep the commands to the bare minimum necessary independent of system configuration.

It's expected of the user to understand how his particular system works. This means that the commands can focus on what's important, rather than making assumptions about the user's system which might be wrong or inaccurate.

**Comment by schrepfler** [comment]
Sure, it's that I saw some sudo's being used in the same file though so perhaps the criteria we have is different. That's cool.

**Comment by chrisduerr** [comment]
If you want to open a PR for cleaning up all remaining `sudo`s in the INSTALL.md, I'd happily get that in.

I think removing the existing uses is a better idea than adding more of it.

**Comment by chrisduerr** [comment]
Shell commands are never intended to be copy-pasted without thinking about them.

If you want to install a package with your distribution, you should be aware that it will require root permissions.

Having `sudo` inside the command, could potentially introduce dangerous side-effects for people who are not properly reading the instructions, modifying global system state without the intention to do so. That's why the default behavior should always be to go without it.

As I've mentioned in my earlier comment, if the desire is to make it obvious to users which commands might require root permissions, then the common annotations should be used:

```
# root command
```
```
$ user command
```

However this should be an additional help to indicate to an aware user what he might have to do to make a command work. It's not intended to do more than give an indication of the authentication level which might be required, which still allows the user himself to make the conscious choice if he wants to run that command with the required permissions or not.

**Pull request closed without merging**
