### PR TITLE
Address VisualBell Feedback

### PR DESCRIPTION
**Pull request by markandrus**
@jonhoo raised some useful feedback in https://github.com/jwilm/alacritty/issues/406, namely

1. Behaviors like "brighten text", "dim text", etc., would be useful.
2. Colors should be customizable to accommodate different color schemes.
3. Non-flashing behaviors like "pixelate" would be useful.

This PR addresses 1 and 2 by converting VisualBellConfig into an enum representing one of three effects:

  * None: does nothing
  * FlashText: flashes the text a configurable color
  * FlashBackground: flashes the background a configurable color

Example video (warning: flashing lights): https://gfycat.com/IdealLazyDairycow

Other changes:

* Renamed VisualBellAnimation to "VisualBellEasing" and `animation` to `easing`.
* Moved the `cubic_bezier` code to src/config.rs and added an `ease` function to the VisualBellEasing implementation.

The VisualBellConfig enum could be expanded in the future to support a Pixelate option, e.g. something like

```yaml
visual_bell:
  Pixelate:
    size: 24 # px
    duration: 150
```

Or perhaps even a Blur could be supported; however, I think these would require adding a rendering pass, so I haven't implemented these yet.

### CODE REVIEW

**Comment by lord-re** [comment]
The flashing background with customizable color is way better than the great white flash !

**Comment by jwilm** [comment]
Thanks for the PR! I've tried this out, and it all works as described. Having control of the flash color is much nicer than _the great white flash_.

I'm not sold on having advanced effects like the text flashing or even more complex effects like pixelate. The color overlay can be implemented concisely. Mostly, I worry about taking on a bunch of code for something simple like the bell.

Going to think on this some more.

**Comment by markandrus** [comment]
> I'm not sold on having advanced effects like the text flashing or even more complex effects like pixelate. The color overlay can be implemented concisely. Mostly, I worry about taking on a bunch of code for something simple like the bell.

Understood 👍 FWIW, I'm just playing around with this feature in order to learn a bit more about Rust (and to play to some degree with OpenGL shaders). I'm happy to explore what _can_ be done, even if  little or none of it should be merged. I'm also happy to cut the text flashing or other parts of the PR if you'd like to accept some form of it.

**Comment by OJFord** [comment]
The `FlashText` option looks fantastic, big :+1: for that.

**Comment by NickeZ** [comment]
It would have been awesome with some more subtle bell like pixelate or blur, but I fully understand that it feels like bloat..

**Comment by pokey** [comment]
@jwilm any updates on this?  All I'd be after is configurable background color for the flash.  This seems like a good compromise between avoiding bloat / addressing the visually disturbing flash for those who dislike it.

**Comment by unphased** [comment]
The great white flash is headache-inducing! I'll take anything that can be configured to be as subtle as i need (which is very subtle). Also nice would be if it could play sound like a bell traditionally does, although I COMPLETELY understand if we want to keep everything simple and visual only for dependency/portability/aesthetic reasons.

**Comment by chrisduerr** [comment]
#963 should implement this.

**Pull request closed without merging**
