### PR TITLE
add freeBSD support on the top

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by chrisduerr** [comment]
I'm no BSD user but I'd imagine if it works in FreeBSD, it will support other BSDs too, right?
If that's the case just saying `BSD` is probably the better idea.

One issue with saying alacritty supports BSD is that it seems to be mostly a coincidence though. There's no CI setup and functionality is not usually tested on BSD. So I'm not quite sure if we should put BSD support on the same level as linux/macos. Maybe at least CI should be added?

What do you think about this @jwilm?

**Comment by ShalokShalom** [comment]
On the bottom it says freeBSD

**Comment by chrisduerr** [comment]
Those are just install instructions that were added in a PR someone has sent iirc. There's no manual or automated testing setup afaik.

I'm not against adding this, it should work fine on BSD, I'd just like to have CI setup if we actually want to make sure it works on BSD.

**Comment by ShalokShalom** [comment]
I mean, if you want BSD instead of freeBSD, maybe consider to respect this section also

**Comment by ShalokShalom** [comment]
So, how to succeed?

**Comment by chrisduerr** [comment]
Waiting for @jwilm to accept/comment.

**Pull request merged**
