### PR TITLE
Fix out of bounds access in glyph buffer.

### PR DESCRIPTION
**Pull request by Capcah**

### CODE REVIEW

**Comment by albertorestifo** [comment]
Can we merge this?

**Comment by jwilm** [comment]
This hasn't been merged because I'd like to figure out why FreeType is telling us the buffer is larger than it actually is.

**Comment by albertorestifo** [comment]
@jwilm is it possible it has something to do with double bytes Unicode characters?

To me it seems to crash only when I use Powerline fonts or ligatures.

**Comment by jwilm** [comment]
This has been addressed in #590

**Pull request closed without merging**
