### PR TITLE
Give zsh completion file the correct name when installing with `cargo deb --install`

### PR DESCRIPTION
**Pull request by alexander255**

### CODE REVIEW

**Comment by chrisduerr** [comment]
I've checked the paths again just to make sure and I've noticed that not only the name is incorrect, but the path is too.

I think it should be `/usr/share/zsh/functions/Completion/X/_alacritty` or `/usr/share/zsh/site_functions/_alacritty` as an alternative.

**Comment by alexander255** [comment]
@chrisduerr: The path I submitted works, but as you said it really belongs into `/usr/share/zsh/functions/Completion/X/_alacritty` (next to `xterm` :wink:). Fixed that and can confirm that it still works. :+1:

**Comment by chrisduerr** [comment]
Note that I'm fine with the state this PR is currently in, however this has caused me to look around again about which locations we should use/recommend for zsh completions.

It seems to me that for Debian-based systems, the standard is `/usr/share/zsh/vendor-completions`.
Since `.deb` is at least slightly Debian related, it probably makes sense to adapt that directory for our zsh completions in the `.deb` file.

Then in the README we recommend installing to `/usr/share/zsh/functions/Completion/X/_alacritty`, however the user shouldn't really be installing completions to this directory (requiring sudo being one indication of this). It seems to me that recommending an alternative like `~/.zsh_functions/` would be a better choice. Then this directory could be added to `$FPATH` in the `~/.zshrc`.

@alexander255 Would you be willing to try making these changes in this PR? I'm pretty sure both things mentioned here are an improvement over the current things we have in place. Any comments on this proposal are welcome of course.

**Comment by alexander255** [comment]
Thanks for investigating this further (I know distro-related work can be quite a PITA…)! I've updated the it to the path you suggested. It is indeed the place where packages install their own (upstream maintained) completion files, `/usr/share/zsh/functions/Completion/*` is just for the stuff in `zsh-common` I guess.

Based on your input I also updated the instructions in the README to recommand creating a local zsh function directory and copy the completion file there.

IMHO, it's also better to maintain the completion files in this repository, if you have the capacity, then to submit them to a central repository where they easily go stale/out-of-sync.

**Comment by alexander255** [comment]
FYI, I've updated https://github.com/jwilm/alacritty/wiki/Installation with the same changes I made to `README.md`.

**Pull request merged**
