### PR TITLE
OSX: Add app packing tooling

### PR DESCRIPTION
**Pull request by cema-sp**
Having **Alacritty.desktop** for Linux users, I thought it would be useful to have some tooling for creating MacOS **Alacritty.app** with release binary.

This _Makefile_ includes targets for creating **Alacritty.app** and **Alacritty.dmg**.

_Info.plist_, simple terminal iconset and launcher script are located in _assets/osx_.

**!** Please note that **Alacritty.app** should be moved to MacOS _Applications_ to start and work correctly.

### CODE REVIEW

**Comment by GlynnKershaw** [comment]
I have built the Alacritty binary, and it's located in _target/release_, but after pulling your commits and running `make app`, I get the error shown in the image that's below. I'm not familiar with macOS development/packaging, so maybe that error is to be expected right now. Still, I may as well mention it.

screen shot 2017-01-12 at 10 51 45

I'd also like to mention that I can run the Alacritty binary from inside **Alacritty.app** by running the **MacOS** binary inside the _Contents_ folder.

**Comment by cema-sp** [comment]
@GlynnKershaw thank you for feedback
It may be security issue (because .app doesn't come from AppStore). Try allowing downloaded apps:
1. http://apple.stackexchange.com/questions/243687/allow-applications-downloaded-from-anywhere-in-macos-sierra
2. http://www.macworld.com/article/3094865/macs/how-to-run-apps-that-are-not-from-the-app-store-in-macos-sierra.html

**Comment by uvesten** [comment]
I don't think it's a security issue. I just built it, and I also get the "damaged or incomplete" warning.
I can run unsigned applications normally, but this is something else. Not even Ctrl+click -> open works.

**Comment by uvesten** [comment]
Found the error. The binary ends up as `Contents/MacOS` instead of `Contents/MacOS/alacritty' 
I'll see if I can make a pull request

**Comment by uvesten** [comment]
@cema-sp Added a pull request to your branch.

**Comment by GlynnKershaw** [comment]
@cema-sp I've applied @uvesten's patch. It now works as one would expect.

screen shot 2017-01-12 at 15 07 27

Looking good.

**Comment by jwilm** [comment]
Thanks for putting this together! I tried this out myself, and it looks like the patch from @uvesten is necessary.

Since Alacritty will now be available in `.app` form, we'll need to figure out how to support multiple windows. In the mean time, an AppleScript in the dock can open as many instances as you like.

```applescript
do shell script "open -n /Applications/Alacritty.app"
```

If anyone knows more about supporting multiple windows for an app in Cocoa, we should talk!

**Comment by cema-sp** [comment]
@uvesten @GlynnKershaw thank you, I realised the issue and fixed it.
Please, try an updated version.

**Comment by cema-sp** [comment]
@jwilm maybe use something like https://github.com/servo/cocoa-rs to create menu and handle other Cocoa things?

**Comment by kazimuth** [comment]
Note that this branch does not support `Cmd-q` (or, really, alacritty in general doesn't support it).

Additionally, note that the app bundle cannot be opened when `shell` is set; I get a `SecTaskLoadEntitlements failed error=22` error in the system console. (However, running `open Alacritty.app` from another terminal does work, for some reason.) Possibly the app is missing an entitlement?

**Comment by tcrayford** [comment]
@kazimuth @jwilm up to y'all, but it seems like this PR is enough of a step in a useful direction. Should we merge it and build on it after that?

**Comment by jwilm** [comment]
For some reason when I start Alacritty with this Alacritty.app, my shell starts from `/`. Anyone else have this issue?

**Comment by kazimuth** [comment]
Same for me, see: http://stackoverflow.com/questions/2202772/what-is-the-pwd-of-a-mac-bundled-app

**Comment by jwilm** [comment]
Sounds like Alacritty needs to change to the user's home directory before spawning the shell process.

**Comment by cema-sp** [comment]
@kazimuth Default MacOS `Cmd+<key>` commands doesn't work for me too (even with `alacritty` binary). To speak about MacOS app entitlements - I have no experience with them.
@jwilm I have the same issue with root path on shell.

**Comment by cema-sp** [comment]
@jwilm @kazimuth added a tiny wrapper to change dir to `$HOME`

**Comment by jbaum98** [comment]
I have an issue where `.profile` is not being sourced when I start the app from Finder. If I run the app from a terminal, the environment variables are inherited and everything is okay, but run from Finder `.zshrc` is being sourced without `.profile` which results in errors. Adding `source .profile` to the launcher script fixes the problem. Should this be added, or is sourcing `.profile` not alcritty's responsibility?

**Comment by NickeZ** [comment]
As soon as we support arguments you can launch the shell with `bash --login` which will source `.profile`

**Comment by jedahan** [comment]
I had to append my $PATH environment variables to the Info.plist for my .zshrc to have it work

```xml
    <key>LSEnvironment</key>
    <dict>
      <key>PATH</key>
      <string>{$REDACTED_PATH}</string>
```

**Comment by felixpalmer** [comment]
Just a note that the above approach does not work on OSX 10.11 (and I suspect earlier). When launching the app a dialog comes up saying that 10.12 is required. Running the app from the command line works fine though. I suspect the issue is similar to that described here http://stackoverflow.com/questions/39310079/mac-app-package-backwards-compatibility-error-you-cant-use-this-version-of-t

**Comment by podgib** [comment]
I've built this branch, but when I try to open the .app package, it fails to open. Running it from the command line gives me the message `LSOpenURLsWithRole() failed with error -10810 for the file ./Alacritty.app`. Any ideas why it won't open? The `alacritty` binary runs fine. 

Running MacOS 10.12.1.

**Comment by cema-sp** [comment]
@podgib the same for me.
~3 weeks earlier HEAD worked well with the same config, but now it doesn't work.

**Comment by podgib** [comment]
@cema-sp I had to do two things to get this to work:

1. Remove the `LSEnvironment` settings from `Info.plist`
2. Remove `"$@"` from the `exec` command in `launcher`

Now the app launches fine

**Comment by cema-sp** [comment]
@podgib thank you for investigating the issue. Removing `"$@"` seems sufficient for the app to work. Could you check, please?

**Comment by lambdalisue** [comment]
It still shows me the error on my environment (Mac OS X Elcapitan). Well, I had a similar problem to make PyMOL.app and that time I ended up to use AppleScript instead (https://github.com/lambdalisue/macosx-pymol-app)

I may send you a PR for the AppleScript version once I confirmed that works.

**Comment by brycefisher** [comment]
This PR is the most exciting thing happening in Alacritty right now in my opinion. Don't stop now!

**Comment by mondras** [comment]
I tried running @cema-sp's branch  with no success getting the same `LSOpenURLsWithRole() failed with error -10810` error people are seeing. Tried finding how to solve it with no success.

Running  ```open target/release/osx/Alacritty.app/Contents/MacOS/launcher``` works. Yet when I run ```./target/release/osx/Alacritty.app/Contents/MacOS/launcher``` the `$BIN_DIR` is incorrect, found that fethcing it with `BIN_DIR=$(cd "$(dirname "$0")"; pwd)` worked for both cases: through open and executing the launcher by itself.

**Comment by brycefisher** [comment]
Since this PR seems to have stalled, I've pulled in the feedback necessary from this thread into another PR https://github.com/jwilm/alacritty/pull/462 that works for me and is rebased against master. I'm happy to merge "my" changes into @cema-sp PR here or have this PR closed in favor of mine. Either way, I'd love to keep this work moving forward.

**Pull request closed without merging**
