### PR TITLE
fix zero-width character rendering

### LINKED ISSUE #1317: Render zero-width characters without progressing the cursor
When zero-width characters are rendered, this should be done without actually progressing the cursor, but rather the character should be rendered above the last cell.

Not only is this important to properly render text, but it can also lead to nasty bugs in applications that manually clear the screen themselves (see #696).

There might already be an issue for this because it has been mentioned multiple times on IRC, but I haven't found one. If someone else is able to find a duplicate of this, please let me know and I can close this one.

### PR DESCRIPTION
**Pull request by doy**
this adds support at the terminal representation level for zero-width characters, which should make zero-width characters not destroy the rendering of ncurses apps, for instance. it also includes a refactoring to support storing multiple codepoints in a single cell - it only renders a single one for now, but it should be a small first step towards #306.

This fixes #1317.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Thanks for opening this PR and sorry for not commenting on it at all for so long. I've taken a quick look at it and have noticed that the main change here is that each cell is now a `SmallVec<char>`.

I can see potential issues in performance and memory usage with this approach, would you be willing to run a few benchmarks on this PR @doy? Using the https://github.com/jwilm/vtebench project it should be simple to get some rough performance numbers.

If there are no big performance or memory issues, I'll take a closer look at the actual code and we'll hopefully be able to get this merged quickly. Thanks again for your work, this has been a long standing issue and I'm really looking forward to a solution.

**Comment by chrisduerr** [comment]
I've benchmarked this myself and it turns out that it introduces a 43% performance decrease compared to the latest master.

**Comment by nixpulvis** [comment]
I'm curious how that looks without the `SmallVec`.

**Comment by chrisduerr** [comment]
@nixpulvis This uses `SmallVec` to store more than one cell. So without the `SmallVec` it would look the same as the current master.

I'd assume that when replacing `SmallVec` with `Vec`, that it would just make these issues worse.

**Comment by nixpulvis** [comment]
I should have been more clear. My curiousity is specifically if there's some weird reason smallvec is slower. But I'm guessing that's not the issue here.

**Comment by chrisduerr** [comment]
I'm not sure @nixpulvis, the best way to figure out the exact reason is probably just by running it through `perf`. But there are a lot of `.clone()`s, which always looks suspicious, so that might be part of the reason.

**Comment by chrisduerr** [comment]
Thanks for your initial pathfinding work, however the performance problems with this approach make it infeasible to merge it. As a result [this](https://github.com/jwilm/alacritty/pull/1880) PR has been created as a more performant replacement.

**Comment by doy** [comment]
great! sorry for not getting around to coming back to this/:

**Comment by chrisduerr** [comment]
No worries! Thanks for working on this and getting the ball rolling!

**Pull request closed without merging**
