### PR TITLE
Keep selection mode when holding button and moving mouse

### PR DESCRIPTION
**Pull request by DivineGod**
There was a bit of talk in #30 about keeping the selection mode when double or triple clicking the mouse button and dragging the selection around, so I had a bit of a try at implementing this.

This is just a rough implementation to get the ball rolling and some more input.

There's one or two more modes, that I'm thinking of implementing, which would require a major rewrite; Column mode and Multiple selections.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for the PR! I just had a chance to test this, and it works really well.

Before merging, I'd like to take a more detailed look at the code than I have time for now. First impression is very positive though.

WRT the other modes, we should probably discuss them before you spend too much time implementing them. I'm kind of allergic to complexity, and the selection stuff already requires a lot of book keeping. Have you thought about what these would look like?

**Comment by DivineGod** [comment]
I have not detailed a fully fledged plan about other modes other than book-keeping by having a list of spans added by `update`. The list should probably not grow unchecked, so for anything but MultiSelection it should be 1-2 `Span`s. Also, don't know if MultiSelection really is something anyone uses.

Column mode needs to share the Cell logic for the Side selection. That's how iTerm does it.

`Selection::span` would need to return `Vec<Span>` probably or `Option<Vec<Span>>`.

`Term::string_from_selection` will also need to change to handle multiple spans.

**Comment by xorgy** [comment]
@jwilm In any case it should be as simple as doing the mode modification at the beginning and the end of the selection. If you start on one word and end on another and you're doing word selection, then you just need to grow the selection to the boundaries of the words. If it's lines, then you simply need to encompass the rest of the starting and ending line. 

If that's complex to implement then something is probably wrong elsewhere. ;- )

**Comment by jwilm** [comment]
Sorry for the delay on landing this feature! I have some time traveling this week when I'll work on it.

Thanks for your patience!

**Comment by jwilm** [comment]
Oh, and thanks for keeping it up-to-date with master. Guess that means you're using the branch. 😉

**Comment by DivineGod** [comment]
@jwilm no worries.

Yeah, I like having the word select boundary work correctly :)

**Comment by jwilm** [comment]
Hey @DivineGod, 

I had a chance to test and review this. The feature worked quite well! However, there were a few parts of the implementation that needed improvements. This is my fault since the original selection abstraction didn't readily support semantic/line dragging modes. Basically, things were too coupled to the `Term` type, and the update API seemed easy to misuse. I was also concerned about how this might be difficult to adapt to the block/multiple selections which you suggested as potential future additions.

Since I was without internet for most of the time spent looking at and testing this, I just went ahead and made an implementation which is now in #626. Want to take it for a spin and let me know what you think?

**Comment by DivineGod** [comment]
@jwilm I just had a quick run and play around with your branch. Looks to be working nicely. I too was a bit iffy about my own implementations potential or lack thereof to be extendable easily. I'll have a more in depth look at the changes in #626 later on today.

I'm going to go ahead and close this in favor of #626

**Comment by jwilm** [comment]
Cool! I look forward to any more feedback you might have. :smile:

**Pull request closed without merging**
