### PR TITLE
Fix issue with some international inputs

### PR DESCRIPTION
**Pull request by jwilm**
cc #87, #55

### CODE REVIEW

**Comment by basile-henry** [comment]
I can confirm this fixes the issue I was having, thanks for the fix! 👍

**Comment by CarwynNelson** [comment]
Issue also reported in #170

**Comment by CarwynNelson** [comment]
Running MacOS 10.12.2. This fix doesn't seem to work for me. I can type the `~` character, which I was able to do on the master branch, but I can't type the `#` character.

Instead the output in my other terminal where I have launched alacritty from just shows `bell` every time I attempt to enter a `#`.

I rebuilt a few times and the problem still persists.

**Comment by jwilm** [comment]
Sounds like this is a net positive; merging.

**Pull request merged**
