### PR TITLE
Add automated i386 docker builds to travis

### PR DESCRIPTION
**Pull request by chrisduerr**
I'm not able to test this myself, so if anyone has access to a 32 bit linux system, please let me know if this binary works:
[alacritty.tar.gz](https://github.com/jwilm/alacritty/files/2546395/alacritty.tar.gz)

### CODE REVIEW

**Comment by dikiaap** [comment]
I'm using Ubuntu 18.04.1 32 bit system. Yes, it's works!

**Comment by chrisduerr** [comment]
@dikiaap Thanks for testing. Can you confirm that there are no error or warning messages printed to the command line when launching Alacritty from a terminal emulator?

**Comment by dikiaap** [comment]
@chrisduerr I have tested my build and the docker build on my machine with default config and it has the same messages

```
[unhandled osc_dispatch]: [['1','2',],['7',],] at line 754
```

**Comment by chrisduerr** [comment]
@dikiaap Thanks for the quick feedback, sounds like everything works great. Thanks for testing!

**Comment by chrisduerr** [comment]
I've tested everything again and all binaries are now properly built. Should be good to go as soon as CI finishes.

**Pull request merged**
