### PR TITLE
Bugfix to rerender the output #540

### PR DESCRIPTION
**Pull request by andys8**
This PR would change the optimization level. I think this is most likely _not_ an option, is it?
Are there other options to fix the behavior?

See comment of @maximbaz for more info <https://github.com/jwilm/alacritty/issues/540#issuecomment-304479048>

### CODE REVIEW

**Comment by chrisduerr** [comment]
> I think this is most likely not an option, is it?

It is not. This is likely a racing condition or something similar. Just making Alacritty slower until the racing condition doesn't pop up anymore is not an option.

I personally can't reproduce the issue at all though, so it's tough for me to look into it.

**Comment by andys8** [comment]
Thanks for the reply. I guess it's very tricky, if the issue is not reproducible. I'm wondering if it's related to i3 or i3 users simply aren't using their mouses often, which trigger's a refresh 😁

**Comment by chrisduerr** [comment]
@andys8 I'm using i3 myself, so I doubt it.

Also just to make sure because your phrasing sounds a bit ambiguous, the #540 issue is about incorrect text getting rendered and actual elements missing.

If you run into issues with Alacritty not refreshing/redrawing when it should, you might want to take a look at #2217.

**Comment by andys8** [comment]
You're right! And I'm happy to read, that it might be solved :) https://github.com/jwilm/alacritty/issues/2217#issuecomment-489367208

**Pull request closed without merging**
